/**
 * DTL Function Registry
 * Single source of truth for all DTL functions used by both the client and the language server.
 * Based on official Sesam DTL documentation: https://docs.sesam.io/hub/data-transformation-language.html
 */

import type {
  DtlCategory,
  DtlFunction,
  DtlFunctionKind,
  DtlParam,
} from "../../types/dtl-registry.types";

export type { DtlCategory, DtlFunction, DtlFunctionKind, DtlParam };

const BASE_DOC_URL = "https://docs.sesam.io/hub/dtl";

// ---------------------------------------------------------------------------
// Category arrays
// ---------------------------------------------------------------------------
const TransformFns = [
  // ─── TRANSFORMS ─────────────────────────────────────────────────────────
  {
    name: "add",
    category: "Transforms",
    kind: "transform",
    signature: "add(property, value)",
    description: "Adds a property with the given value to the target entity.",
    params: [
      {
        name: "property",
        description: "The property name to set on the target entity.",
      },
      { name: "value", description: "The value to assign to the property." },
    ],
    minArgs: 2,
    maxArgs: 2,
    docUrl: `${BASE_DOC_URL}/dtl-functions-transforms.html`,
  },
  {
    name: "add-if",
    category: "Transforms",
    kind: "transform",
    signature: "add-if(property [, condition], value)",
    description:
      "Adds PROPERTY to the target entity with VALUE if the optional CONDITION is truthy (defaults to non-null check).",
    params: [
      {
        name: "property",
        description: "The property name to set on the target entity.",
      },
      {
        name: "condition",
        optional: true,
        description: "Optional boolean expression; defaults to non-null check on value.",
      },
      {
        name: "value",
        description: "The value to assign. Property is not set if condition is falsy.",
      },
    ],
    minArgs: 2,
    maxArgs: 3,
    docUrl: `${BASE_DOC_URL}/dtl-functions-transforms.html`,
  },
  {
    name: "copy",
    category: "Transforms",
    kind: "transform",
    signature: "copy(include [, exclude])",
    description:
      "Copies properties matching INCLUDE from the source entity to the target entity. Properties matching EXCLUDE are omitted.",
    params: [
      {
        name: "include",
        description: 'Property name or wildcard pattern(s) to include (e.g. "*").',
      },
      {
        name: "exclude",
        optional: true,
        description: "Property name or wildcard pattern(s) to exclude.",
      },
    ],
    minArgs: 1,
    maxArgs: 2,
    docUrl: `${BASE_DOC_URL}/dtl-functions-transforms.html`,
  },
  {
    name: "default",
    category: "Transforms",
    kind: "transform",
    signature: "default(property, value)",
    description: "Sets a property on the target entity only if it is not already set.",
    params: [
      { name: "property", description: "The property name." },
      { name: "value", description: "The default value." },
    ],
    minArgs: 2,
    maxArgs: 2,
    docUrl: `${BASE_DOC_URL}/dtl-functions-transforms.html`,
  },
  {
    name: "make-ni",
    category: "Transforms",
    kind: "transform",
    signature: "make-ni(namespace, from-property [, to-property])",
    description:
      "Adds FROM_PROPERTY as namespaced identifiers in NAMESPACE to the target entity. TO_PROPERTY defaults to FROM_PROPERTY + '-ni'.",
    params: [
      { name: "namespace", description: "Namespace string." },
      { name: "from-property", description: "Source property name whose values are namespaced." },
      {
        name: "to-property",
        optional: true,
        description: "Target property name. Defaults to from-property + '-ni'.",
      },
    ],
    minArgs: 2,
    maxArgs: 3,
    docUrl: `${BASE_DOC_URL}/dtl-functions-transforms.html`,
  },
  {
    name: "merge",
    category: "Transforms",
    kind: "transform",
    signature: "merge(source)",
    description: "Merges all properties from the given dict/entity into the target entity.",
    params: [
      {
        name: "source",
        description: "A dict or entity whose properties are merged.",
      },
    ],
    minArgs: 1,
    maxArgs: 1,
    docUrl: `${BASE_DOC_URL}/dtl-functions-transforms.html`,
  },
  {
    name: "merge-union",
    category: "Transforms",
    kind: "transform",
    signature: "merge-union(source)",
    description: "Merges properties using union semantics — existing list values are unioned.",
    params: [{ name: "source", description: "A dict or entity." }],
    minArgs: 1,
    maxArgs: 1,
    docUrl: `${BASE_DOC_URL}/dtl-functions-transforms.html`,
  },
  {
    name: "remove",
    category: "Transforms",
    kind: "transform",
    signature: "remove(property-or-wildcard)",
    description: "Removes one or more properties from the target entity.",
    params: [
      {
        name: "property-or-wildcard",
        description: "Property name or wildcard.",
      },
    ],
    minArgs: 1,
    maxArgs: 1,
    docUrl: `${BASE_DOC_URL}/dtl-functions-transforms.html`,
  },
  {
    name: "rename",
    category: "Transforms",
    kind: "transform",
    signature: "rename(new-name, old-name)",
    description: "Copies a property from old-name to new-name on the target entity.",
    params: [
      { name: "new-name", description: "New property name." },
      { name: "old-name", description: "Source property path." },
    ],
    minArgs: 2,
    maxArgs: 2,
    docUrl: `${BASE_DOC_URL}/dtl-functions-transforms.html`,
  },
  {
    name: "create",
    category: "Transforms",
    kind: "transform",
    signature: "create(values)",
    description: "For each entity in VALUES emits it as a new root entity in the output pipeline.",
    params: [
      {
        name: "values",
        description: "A value expression yielding the entity or entities to emit.",
      },
    ],
    minArgs: 1,
    maxArgs: 1,
    docUrl: `${BASE_DOC_URL}/dtl-functions-transforms.html`,
  },
  {
    name: "create-child",
    category: "Transforms",
    kind: "transform",
    signature: "create-child(values)",
    description:
      "For each entity in VALUES adds it to the $children property on the target entity.",
    params: [
      {
        name: "values",
        description: "A value expression yielding the entity or entities to add as children.",
      },
    ],
    minArgs: 1,
    maxArgs: 1,
    docUrl: `${BASE_DOC_URL}/dtl-functions-transforms.html`,
  },
  {
    name: "filter",
    category: "Transforms",
    // filter is overloaded: as a transform it drops the current entity (0–1 args);
    // as a list expression it filters a list (2 args: function + values).
    kind: "expression",
    signature: "filter([condition]) | filter(function, values)",
    description:
      "As a transform: discards the current entity if CONDITION is falsy (or unconditionally if omitted). " +
      "As a list expression: returns the elements of VALUES for which FUNCTION evaluates to true.",
    params: [
      {
        name: "condition / function",
        description:
          "Transform variant: boolean condition (optional). Expression variant: function applied to each element (use _ for current).",
      },
      {
        name: "values",
        optional: true,
        description: "Expression variant: the list to filter.",
      },
    ],
    minArgs: 0,
    maxArgs: 2,
    docUrl: `${BASE_DOC_URL}/dtl-functions-transforms.html`,
  },
  {
    name: "discard",
    category: "Transforms",
    kind: "transform",
    signature: "discard([unless-condition])",
    description:
      "Drops the target entity. If UNLESS_CONDITION is given and evaluates to true, the entity is kept.",
    params: [
      {
        name: "unless-condition",
        optional: true,
        description: "If this expression is true the entity is NOT discarded.",
      },
    ],
    minArgs: 0,
    maxArgs: 1,
    docUrl: `${BASE_DOC_URL}/dtl-functions-transforms.html`,
  },
  {
    name: "if",
    category: "Transforms",
    kind: "transform",
    signature: "if(condition, then [, else])",
    description:
      "Conditionally applies a transform: executes `then` when condition is truthy, `else` otherwise.",
    params: [
      { name: "condition", description: "Boolean expression." },
      {
        name: "then",
        description: "Transform to apply when condition is true.",
      },
      {
        name: "else",
        description: "Transform to apply when condition is false.",
        optional: true,
      },
    ],
    minArgs: 2,
    maxArgs: 3,
    docUrl: `${BASE_DOC_URL}/dtl-functions-transforms.html`,
  },
  {
    name: "case",
    category: "Transforms",
    kind: "transform",
    signature: "case([condition, transform, ...] [, default-transform])",
    description: "Evaluates each condition in order and applies the first matching transform.",
    params: [
      {
        name: "...pairs",
        description: "Alternating condition/transform pairs, optional default at end.",
      },
    ],
    minArgs: 1,
    maxArgs: null,
    docUrl: `${BASE_DOC_URL}/dtl-functions-transforms.html`,
  },
  {
    name: "case-eq",
    category: "Transforms",
    kind: "transform",
    signature: "case-eq(value, [match, transform, ...] [, default-transform])",
    description: "Compares value against each match and applies the first matching transform.",
    params: [
      { name: "value", description: "The value to compare." },
      {
        name: "...pairs",
        description: "Alternating match/transform pairs, optional default at end.",
      },
    ],
    minArgs: 2,
    maxArgs: null,
    docUrl: `${BASE_DOC_URL}/dtl-functions-transforms.html`,
  },
  {
    name: "comment",
    category: "Transforms",
    kind: "transform",
    signature: "comment(text, ...)",
    description:
      "A no-op transform used for inline documentation. Any number of comment lines can be given.",
    params: [{ name: "text", optional: true, description: "Comment text (ignored at runtime)." }],
    minArgs: 0,
    maxArgs: null,
    docUrl: `${BASE_DOC_URL}/dtl-functions-transforms.html`,
  },
  {
    name: "fail!",
    category: "Transforms",
    kind: "transform",
    signature: "fail!(message)",
    description: "Raises an error and aborts processing of the current entity.",
    params: [{ name: "message", description: "Error message string." }],
    minArgs: 0,
    maxArgs: 1,
    docUrl: `${BASE_DOC_URL}/dtl-functions-transforms.html`,
  },
  {
    name: "sleep!",
    category: "Transforms",
    kind: "transform",
    signature: "sleep!(milliseconds)",
    description: "Pauses processing for the given number of milliseconds.",
    params: [{ name: "milliseconds", description: "Sleep duration in ms." }],
    minArgs: 1,
    maxArgs: 1,
    docUrl: `${BASE_DOC_URL}/dtl-functions-transforms.html`,
  },
  {
    name: "trip!",
    category: "Transforms",
    kind: "transform",
    signature: "trip!(message)",
    description: "Marks the pump as failed with the given message without discarding the entity.",
    params: [{ name: "message", description: "Error message string." }],
    minArgs: 0,
    maxArgs: 1,
    docUrl: `${BASE_DOC_URL}/dtl-functions-transforms.html`,
  },
] as const satisfies readonly DtlFunction[];

const BooleanLogicFns = [
  // ─── BOOLEAN LOGIC ───────────────────────────────────────────────────────
  {
    name: "and",
    category: "Boolean logic",
    kind: "expression",
    signature: "and(expr, ...)",
    description: "Returns true if all expressions are truthy.",
    params: [{ name: "expr", description: "One or more boolean expressions." }],
    minArgs: 1,
    maxArgs: null,
    docUrl: `${BASE_DOC_URL}/dtl-functions-boolean-logic.html`,
  },
  {
    name: "or",
    category: "Boolean logic",
    kind: "expression",
    signature: "or(expr, ...)",
    description: "Returns true if at least one expression is truthy.",
    params: [{ name: "expr", description: "One or more boolean expressions." }],
    minArgs: 1,
    maxArgs: null,
    docUrl: `${BASE_DOC_URL}/dtl-functions-boolean-logic.html`,
  },
  {
    name: "not",
    category: "Boolean logic",
    kind: "expression",
    signature: "not(expr)",
    description: "Returns the logical negation of the expression.",
    params: [{ name: "expr", description: "A boolean expression." }],
    minArgs: 1,
    maxArgs: 1,
    docUrl: `${BASE_DOC_URL}/dtl-functions-boolean-logic.html`,
  },
  {
    name: "all",
    category: "Boolean logic",
    kind: "expression",
    signature: "all(list, condition)",
    description: "Returns true if all items in the list satisfy the condition.",
    params: [
      { name: "list", description: "A list to iterate over." },
      { name: "condition", description: "A boolean expression using _." },
    ],
    minArgs: 2,
    maxArgs: 2,
    docUrl: `${BASE_DOC_URL}/dtl-functions-boolean-logic.html`,
  },
  {
    name: "any",
    category: "Boolean logic",
    kind: "expression",
    signature: "any(list, condition)",
    description: "Returns true if any item in the list satisfies the condition.",
    params: [
      { name: "list", description: "A list to iterate over." },
      { name: "condition", description: "A boolean expression using _." },
    ],
    minArgs: 2,
    maxArgs: 2,
    docUrl: `${BASE_DOC_URL}/dtl-functions-boolean-logic.html`,
  },
] as const satisfies readonly DtlFunction[];

const BooleanFns = [
  // ─── BOOLEANS ────────────────────────────────────────────────────────────
  {
    name: "boolean",
    category: "Booleans",
    kind: "expression",
    signature: "boolean(value)",
    description: "Casts value to a boolean.",
    params: [{ name: "value", description: "The value to cast." }],
    minArgs: 1,
    maxArgs: 1,
    docUrl: `${BASE_DOC_URL}/dtl-functions-booleans.html`,
  },
  {
    name: "is-boolean",
    category: "Booleans",
    kind: "expression",
    signature: "is-boolean(value)",
    description: "Returns true if value is a boolean.",
    params: [{ name: "value", description: "The value to test." }],
    minArgs: 1,
    maxArgs: 1,
    docUrl: `${BASE_DOC_URL}/dtl-functions-booleans.html`,
  },
] as const satisfies readonly DtlFunction[];

const BytesFns = [
  // ─── BYTES ───────────────────────────────────────────────────────────────
  {
    name: "base64-encode",
    category: "Bytes",
    kind: "expression",
    signature: "base64-encode(value)",
    description: "Encodes value as a Base64 string.",
    params: [{ name: "value", description: "Bytes or string to encode." }],
    minArgs: 1,
    maxArgs: 1,
    docUrl: `${BASE_DOC_URL}/dtl-functions-bytes.html`,
  },
  {
    name: "base64-decode",
    category: "Bytes",
    kind: "expression",
    signature: "base64-decode(value)",
    description: "Decodes a Base64-encoded string to bytes.",
    params: [{ name: "value", description: "Base64 string to decode." }],
    minArgs: 1,
    maxArgs: 1,
    docUrl: `${BASE_DOC_URL}/dtl-functions-bytes.html`,
  },
  {
    name: "bytes",
    category: "Bytes",
    kind: "expression",
    signature: "bytes(value)",
    description: "Converts a value to bytes.",
    params: [{ name: "value", description: "String or integer list." }],
    minArgs: 1,
    maxArgs: 1,
    docUrl: `${BASE_DOC_URL}/dtl-functions-bytes.html`,
  },
  {
    name: "is-bytes",
    category: "Bytes",
    kind: "expression",
    signature: "is-bytes(value)",
    description: "Returns true if value is a bytes object.",
    params: [{ name: "value", description: "The value to test." }],
    minArgs: 1,
    maxArgs: 1,
    docUrl: `${BASE_DOC_URL}/dtl-functions-bytes.html`,
  },
] as const satisfies readonly DtlFunction[];

const ComparisonFns = [
  // ─── COMPARISONS ─────────────────────────────────────────────────────────
  {
    name: "eq",
    category: "Comparisons",
    kind: "expression",
    signature: "eq(a, b)",
    description: "Returns true if a equals b.",
    params: [
      { name: "a", description: "Left operand." },
      { name: "b", description: "Right operand." },
    ],
    minArgs: 2,
    maxArgs: 2,
    docUrl: `${BASE_DOC_URL}/dtl-functions-comparisons.html`,
  },
  {
    name: "neq",
    category: "Comparisons",
    kind: "expression",
    signature: "neq(a, b)",
    description: "Returns true if a is not equal to b.",
    params: [
      { name: "a", description: "Left operand." },
      { name: "b", description: "Right operand." },
    ],
    minArgs: 2,
    maxArgs: 2,
    docUrl: `${BASE_DOC_URL}/dtl-functions-comparisons.html`,
  },
  {
    name: "gt",
    category: "Comparisons",
    kind: "expression",
    signature: "gt(a, b)",
    description: "Returns true if a is greater than b.",
    params: [
      { name: "a", description: "Left operand." },
      { name: "b", description: "Right operand." },
    ],
    minArgs: 2,
    maxArgs: 2,
    docUrl: `${BASE_DOC_URL}/dtl-functions-comparisons.html`,
  },
  {
    name: "gte",
    category: "Comparisons",
    kind: "expression",
    signature: "gte(a, b)",
    description: "Returns true if a is greater than or equal to b.",
    params: [
      { name: "a", description: "Left operand." },
      { name: "b", description: "Right operand." },
    ],
    minArgs: 2,
    maxArgs: 2,
    docUrl: `${BASE_DOC_URL}/dtl-functions-comparisons.html`,
  },
  {
    name: "lt",
    category: "Comparisons",
    kind: "expression",
    signature: "lt(a, b)",
    description: "Returns true if a is less than b.",
    params: [
      { name: "a", description: "Left operand." },
      { name: "b", description: "Right operand." },
    ],
    minArgs: 2,
    maxArgs: 2,
    docUrl: `${BASE_DOC_URL}/dtl-functions-comparisons.html`,
  },
  {
    name: "lte",
    category: "Comparisons",
    kind: "expression",
    signature: "lte(a, b)",
    description: "Returns true if a is less than or equal to b.",
    params: [
      { name: "a", description: "Left operand." },
      { name: "b", description: "Right operand." },
    ],
    minArgs: 2,
    maxArgs: 2,
    docUrl: `${BASE_DOC_URL}/dtl-functions-comparisons.html`,
  },
] as const satisfies readonly DtlFunction[];

const ConditionalFns = [
  // ─── CONDITIONALS ────────────────────────────────────────────────────────
  {
    name: "coalesce",
    category: "Conditionals",
    kind: "expression",
    signature: "coalesce(expr, ...)",
    description: "Returns the first non-null, non-empty value from the arguments.",
    params: [{ name: "expr", description: "One or more expressions to evaluate." }],
    minArgs: 1,
    maxArgs: null,
    docUrl: `${BASE_DOC_URL}/dtl-functions-conditionals.html`,
  },
  {
    name: "coalesce-args",
    category: "Conditionals",
    kind: "expression",
    signature: "coalesce-args(expr, ...)",
    description: "Returns the first non-null argument (does not flatten lists).",
    params: [{ name: "expr", description: "One or more expressions." }],
    minArgs: 1,
    maxArgs: null,
    docUrl: `${BASE_DOC_URL}/dtl-functions-conditionals.html`,
  },
] as const satisfies readonly DtlFunction[];

const DateTimeFns = [
  // ─── DATE AND TIME ───────────────────────────────────────────────────────
  {
    name: "now",
    category: "Date and time",
    kind: "expression",
    signature: "now()",
    description: "Returns the current UTC datetime.",
    params: [],
    minArgs: 0,
    maxArgs: 0,
    docUrl: `${BASE_DOC_URL}/dtl-functions-date-and-time.html`,
  },
  {
    name: "datetime",
    category: "Date and time",
    kind: "expression",
    signature: "datetime(value)",
    description: "Parses or converts value to a datetime object.",
    params: [{ name: "value", description: "ISO 8601 string or transit datetime." }],
    minArgs: 1,
    maxArgs: 1,
    docUrl: `${BASE_DOC_URL}/dtl-functions-date-and-time.html`,
  },
  {
    name: "datetime-parse",
    category: "Date and time",
    kind: "expression",
    signature: "datetime-parse(format, value)",
    description: "Parses value with the given format string to a datetime.",
    params: [
      { name: "format", description: "strptime-compatible format string." },
      { name: "value", description: "The string to parse." },
    ],
    minArgs: 2,
    maxArgs: 2,
    docUrl: `${BASE_DOC_URL}/dtl-functions-date-and-time.html`,
  },
  {
    name: "datetime-format",
    category: "Date and time",
    kind: "expression",
    signature: "datetime-format(format, datetime [, timezone])",
    description: "Formats a datetime value using the given format string.",
    params: [
      { name: "format", description: "strftime-compatible format string." },
      { name: "datetime", description: "A datetime value." },
      {
        name: "timezone",
        description: "Optional timezone identifier.",
        optional: true,
      },
    ],
    minArgs: 2,
    maxArgs: 3,
    docUrl: `${BASE_DOC_URL}/dtl-functions-date-and-time.html`,
  },
  {
    name: "datetime-diff",
    category: "Date and time",
    kind: "expression",
    signature: "datetime-diff(unit, datetime1, datetime2)",
    description: "Returns the difference between two datetimes in the given unit.",
    params: [
      {
        name: "unit",
        description: '"days", "hours", "minutes", "seconds", etc.',
      },
      { name: "datetime1", description: "First datetime." },
      { name: "datetime2", description: "Second datetime." },
    ],
    minArgs: 3,
    maxArgs: 3,
    docUrl: `${BASE_DOC_URL}/dtl-functions-date-and-time.html`,
  },
  {
    name: "datetime-plus",
    category: "Date and time",
    kind: "expression",
    signature: "datetime-plus(datetime, unit, amount)",
    description: "Adds amount of unit to the given datetime.",
    params: [
      { name: "datetime", description: "A datetime value." },
      {
        name: "unit",
        description: '"days", "hours", "minutes", "seconds", etc.',
      },
      { name: "amount", description: "Number to add (can be negative)." },
    ],
    minArgs: 3,
    maxArgs: 3,
    docUrl: `${BASE_DOC_URL}/dtl-functions-date-and-time.html`,
  },
  {
    name: "datetime-shift",
    category: "Date and time",
    kind: "expression",
    signature: "datetime-shift(datetime, from-timezone, to-timezone)",
    description: "Shifts a datetime between timezones.",
    params: [
      { name: "datetime", description: "A datetime value." },
      { name: "from-timezone", description: "Source timezone identifier." },
      { name: "to-timezone", description: "Target timezone identifier." },
    ],
    minArgs: 3,
    maxArgs: 3,
    docUrl: `${BASE_DOC_URL}/dtl-functions-date-and-time.html`,
  },
  {
    name: "is-datetime",
    category: "Date and time",
    kind: "expression",
    signature: "is-datetime(value)",
    description: "Returns true if value is a datetime object.",
    params: [{ name: "value", description: "The value to test." }],
    minArgs: 1,
    maxArgs: 1,
    docUrl: `${BASE_DOC_URL}/dtl-functions-date-and-time.html`,
  },
] as const satisfies readonly DtlFunction[];

const DictionaryFns = [
  // ─── DICTIONARIES ────────────────────────────────────────────────────────
  {
    name: "dict",
    category: "Dictionaries",
    kind: "expression",
    signature: "dict(key, value, ...)",
    description: "Creates a dictionary from alternating key-value arguments.",
    params: [{ name: "key-value-pairs", description: "Alternating keys and values." }],
    minArgs: 0,
    maxArgs: null,
    docUrl: `${BASE_DOC_URL}/dtl-functions-dictionaries.html`,
  },
  {
    name: "keys",
    category: "Dictionaries",
    kind: "expression",
    signature: "keys(dict)",
    description: "Returns the keys of a dictionary as a list.",
    params: [{ name: "dict", description: "A dictionary value." }],
    minArgs: 1,
    maxArgs: 1,
    docUrl: `${BASE_DOC_URL}/dtl-functions-dictionaries.html`,
  },
  {
    name: "values",
    category: "Dictionaries",
    kind: "expression",
    signature: "values(dict)",
    description: "Returns the values of a dictionary as a list.",
    params: [{ name: "dict", description: "A dictionary value." }],
    minArgs: 1,
    maxArgs: 1,
    docUrl: `${BASE_DOC_URL}/dtl-functions-dictionaries.html`,
  },
  {
    name: "items",
    category: "Dictionaries",
    kind: "expression",
    signature: "items(dict)",
    description: "Returns key-value pairs of a dictionary as a list of [key, value] lists.",
    params: [{ name: "dict", description: "A dictionary value." }],
    minArgs: 1,
    maxArgs: 1,
    docUrl: `${BASE_DOC_URL}/dtl-functions-dictionaries.html`,
  },
  {
    name: "key-values",
    category: "Dictionaries",
    kind: "expression",
    signature: "key-values(dict)",
    description: 'Returns key-value pairs as a list of {"key":k,"value":v} dicts.',
    params: [{ name: "dict", description: "A dictionary value." }],
    minArgs: 1,
    maxArgs: 1,
    docUrl: `${BASE_DOC_URL}/dtl-functions-dictionaries.html`,
  },
  {
    name: "has-key",
    category: "Dictionaries",
    kind: "expression",
    signature: "has-key(dict, key)",
    description: "Returns true if the dictionary contains the given key.",
    params: [
      { name: "dict", description: "A dictionary value." },
      { name: "key", description: "Key to check." },
    ],
    minArgs: 2,
    maxArgs: 2,
    docUrl: `${BASE_DOC_URL}/dtl-functions-dictionaries.html`,
  },
  {
    name: "is-dict",
    category: "Dictionaries",
    kind: "expression",
    signature: "is-dict(value)",
    description: "Returns true if value is a dictionary.",
    params: [{ name: "value", description: "The value to test." }],
    minArgs: 1,
    maxArgs: 1,
    docUrl: `${BASE_DOC_URL}/dtl-functions-dictionaries.html`,
  },
  {
    name: "path",
    category: "Dictionaries",
    kind: "expression",
    signature: "path(path, value)",
    description: "Follows a dot-separated path into a nested dict structure.",
    params: [
      { name: "path", description: "Dot-separated key path string." },
      { name: "value", description: "The dict or entity to traverse." },
    ],
    minArgs: 2,
    maxArgs: 2,
    docUrl: `${BASE_DOC_URL}/dtl-functions-dictionaries.html`,
  },
  {
    name: "apply",
    category: "Dictionaries",
    kind: "expression",
    signature: "apply(rule-id, entity)",
    description: "Applies a named DTL rule (defined in the same pipe) to an entity.",
    params: [
      { name: "rule-id", description: "The rule identifier string." },
      { name: "entity", description: "The entity to transform." },
    ],
    minArgs: 2,
    maxArgs: 2,
    docUrl: `${BASE_DOC_URL}/dtl-functions-dictionaries.html`,
  },
  {
    name: "apply-hops",
    category: "Dictionaries",
    kind: "expression",
    signature: "apply-hops(rule-id, hops-spec)",
    description: "Applies a named rule to entities fetched via hops.",
    params: [
      { name: "rule-id", description: "The rule identifier string." },
      { name: "hops-spec", description: "A hops specification object." },
    ],
    minArgs: 2,
    maxArgs: 2,
    docUrl: `${BASE_DOC_URL}/dtl-functions-dictionaries.html`,
  },
  {
    name: "apply-ns",
    category: "Dictionaries",
    kind: "expression",
    signature: "apply-ns(namespace, dict)",
    description: "Applies a namespace to all keys in a dictionary.",
    params: [
      {
        name: "namespace",
        description: "Namespace string to prefix keys with.",
      },
      { name: "dict", description: "A dictionary." },
    ],
    minArgs: 2,
    maxArgs: 2,
    docUrl: `${BASE_DOC_URL}/dtl-functions-dictionaries.html`,
  },
  {
    name: "strip-ns",
    category: "Dictionaries",
    kind: "expression",
    signature: "strip-ns(dict)",
    description: "Removes namespace prefixes from all keys in a dictionary.",
    params: [{ name: "dict", description: "A dictionary with namespaced keys." }],
    minArgs: 1,
    maxArgs: 1,
    docUrl: `${BASE_DOC_URL}/dtl-functions-dictionaries.html`,
  },
] as const satisfies readonly DtlFunction[];

const EncryptionFns = [
  // ─── ENCRYPTION ──────────────────────────────────────────────────────────
  {
    name: "encrypt",
    category: "Encryption",
    kind: "expression",
    signature: "encrypt(value)",
    description: "Encrypts a value using the datahub encryption key.",
    params: [{ name: "value", description: "The value to encrypt." }],
    minArgs: 1,
    maxArgs: 1,
    docUrl: `${BASE_DOC_URL}/dtl-functions-encryption.html`,
  },
  {
    name: "decrypt",
    category: "Encryption",
    kind: "expression",
    signature: "decrypt(value)",
    description: "Decrypts a value encrypted with the datahub encryption key.",
    params: [{ name: "value", description: "The encrypted value to decrypt." }],
    minArgs: 1,
    maxArgs: 1,
    docUrl: `${BASE_DOC_URL}/dtl-functions-encryption.html`,
  },
  {
    name: "encrypt-pgp",
    category: "Encryption",
    kind: "expression",
    signature: "encrypt-pgp(public-key, value)",
    description: "Encrypts value using PGP public key encryption.",
    params: [
      { name: "public-key", description: "PGP public key string." },
      { name: "value", description: "The value to encrypt." },
    ],
    minArgs: 2,
    maxArgs: 2,
    docUrl: `${BASE_DOC_URL}/dtl-functions-encryption.html`,
  },
  {
    name: "decrypt-pgp",
    category: "Encryption",
    kind: "expression",
    signature: "decrypt-pgp(private-key, value)",
    description: "Decrypts a PGP-encrypted value.",
    params: [
      { name: "private-key", description: "PGP private key string." },
      { name: "value", description: "The encrypted value." },
    ],
    minArgs: 2,
    maxArgs: 2,
    docUrl: `${BASE_DOC_URL}/dtl-functions-encryption.html`,
  },
  {
    name: "encrypt-pki",
    category: "Encryption",
    kind: "expression",
    signature: "encrypt-pki(public-key, value)",
    description: "Encrypts value using PKI public key encryption.",
    params: [
      { name: "public-key", description: "PKI public key string." },
      { name: "value", description: "The value to encrypt." },
    ],
    minArgs: 2,
    maxArgs: 2,
    docUrl: `${BASE_DOC_URL}/dtl-functions-encryption.html`,
  },
  {
    name: "decrypt-pki",
    category: "Encryption",
    kind: "expression",
    signature: "decrypt-pki(private-key, value)",
    description: "Decrypts a PKI-encrypted value.",
    params: [
      { name: "private-key", description: "PKI private key string." },
      { name: "value", description: "The encrypted value." },
    ],
    minArgs: 2,
    maxArgs: 2,
    docUrl: `${BASE_DOC_URL}/dtl-functions-encryption.html`,
  },
] as const satisfies readonly DtlFunction[];

const HopsFns = [
  // ─── HOPS ────────────────────────────────────────────────────────────────
  {
    name: "hops",
    category: "Hops",
    kind: "expression",
    signature: "hops(hops-spec)",
    description: "Performs a hop to retrieve related entities from another dataset.",
    params: [
      {
        name: "hops-spec",
        description: 'Object with "datasets", "where", and optionally "return" and "max-depth".',
      },
    ],
    minArgs: 1,
    maxArgs: 1,
    docUrl: `${BASE_DOC_URL}/dtl-functions-hops.html`,
  },
  {
    name: "lookup-entity",
    category: "Hops",
    kind: "expression",
    signature: "lookup-entity(dataset, id)",
    description: "Retrieves a single entity by _id from the given dataset.",
    params: [
      { name: "dataset", description: "Dataset name string." },
      { name: "id", description: "The _id value to look up." },
    ],
    minArgs: 2,
    maxArgs: 2,
    docUrl: `${BASE_DOC_URL}/dtl-functions-hops.html`,
  },
] as const satisfies readonly DtlFunction[];

const JsonFns = [
  // ─── JSON ────────────────────────────────────────────────────────────────
  {
    name: "json",
    category: "JSON",
    kind: "expression",
    signature: "json(value)",
    description: "Serializes value to a JSON string.",
    params: [{ name: "value", description: "The value to serialize." }],
    minArgs: 1,
    maxArgs: 1,
    docUrl: `${BASE_DOC_URL}/dtl-functions-json.html`,
  },
  {
    name: "json-parse",
    category: "JSON",
    kind: "expression",
    signature: "json-parse(string)",
    description: "Parses a JSON string into a value.",
    params: [{ name: "string", description: "A JSON-encoded string." }],
    minArgs: 1,
    maxArgs: 1,
    docUrl: `${BASE_DOC_URL}/dtl-functions-json.html`,
  },
  {
    name: "json-transit",
    category: "JSON",
    kind: "expression",
    signature: "json-transit(value)",
    description: "Serializes value using JSON Transit encoding.",
    params: [{ name: "value", description: "The value to encode." }],
    minArgs: 1,
    maxArgs: 1,
    docUrl: `${BASE_DOC_URL}/dtl-functions-json.html`,
  },
  {
    name: "json-transit-parse",
    category: "JSON",
    kind: "expression",
    signature: "json-transit-parse(string)",
    description: "Parses a JSON Transit-encoded string.",
    params: [{ name: "string", description: "A JSON Transit string." }],
    minArgs: 1,
    maxArgs: 1,
    docUrl: `${BASE_DOC_URL}/dtl-functions-json.html`,
  },
] as const satisfies readonly DtlFunction[];

const ListFns = [
  // ─── LISTS ───────────────────────────────────────────────────────────────
  {
    name: "list",
    category: "Lists",
    kind: "expression",
    signature: "list(value, ...)",
    description: "Creates a list from the given values.",
    params: [{ name: "value", description: "One or more values." }],
    minArgs: 0,
    maxArgs: null,
    docUrl: `${BASE_DOC_URL}/dtl-functions-lists.html`,
  },
  {
    name: "map",
    category: "Lists",
    kind: "expression",
    signature: "map(function, values)",
    description:
      'For each value in VALUES apply FUNCTION and construct a new list of the return values. Use "_." inside FUNCTION to reference the current element.',
    params: [
      {
        name: "function",
        description: 'Expression applied to each element (use "_." for the current element).',
      },
      { name: "values", description: "A list to iterate over." },
    ],
    minArgs: 2,
    maxArgs: 2,
    docUrl: `${BASE_DOC_URL}/dtl-functions-lists.html`,
  },
  {
    name: "map-dict",
    category: "Lists",
    kind: "expression",
    signature: "map-dict(key-fn, value-fn, values)",
    description:
      'For each dictionary in VALUES construct a new dictionary by applying KEY_FN and VALUE_FN to all its key+value pairs. Inside KEY_FN, "_." refers to the key; inside VALUE_FN it refers to the value. If KEY_FN returns a non-string, that pair is skipped. Empty dictionaries are not returned.',
    params: [
      { name: "key-fn", description: 'Expression producing the output key ("_." = current key).' },
      {
        name: "value-fn",
        description: 'Expression producing the output value ("_." = current value).',
      },
      { name: "values", description: "A dictionary or list of dictionaries." },
    ],
    minArgs: 3,
    maxArgs: 3,
    docUrl: `${BASE_DOC_URL}/dtl-functions-lists.html`,
  },
  {
    name: "map-values",
    category: "Lists",
    kind: "expression",
    signature: "map-values(function, values)",
    description:
      "For each dictionary in VALUES apply FUNCTION to all the dictionary's values. Non-dictionary values are ignored. Returns a flat list of all the mapped values (not a dictionary).",
    params: [
      { name: "function", description: 'Expression applied to each value ("_." = current value).' },
      { name: "values", description: "A dictionary or list of dictionaries." },
    ],
    minArgs: 2,
    maxArgs: 2,
    docUrl: `${BASE_DOC_URL}/dtl-functions-lists.html`,
  },
  {
    name: "first",
    category: "Lists",
    kind: "expression",
    signature: "first(list)",
    description: "Returns the first element of the list, or null if empty.",
    params: [{ name: "list", description: "A list value." }],
    minArgs: 1,
    maxArgs: 1,
    docUrl: `${BASE_DOC_URL}/dtl-functions-lists.html`,
  },
  {
    name: "last",
    category: "Lists",
    kind: "expression",
    signature: "last(list)",
    description: "Returns the last element of the list, or null if empty.",
    params: [{ name: "list", description: "A list value." }],
    minArgs: 1,
    maxArgs: 1,
    docUrl: `${BASE_DOC_URL}/dtl-functions-lists.html`,
  },
  {
    name: "nth",
    category: "Lists",
    kind: "expression",
    signature: "nth(index, values)",
    description:
      "Returns the value at zero-based INDEX in VALUES. If VALUES is not a sequence it is returned only when INDEX is 0. Returns null when empty or out of bounds.",
    params: [
      { name: "index", description: "Zero-based position to retrieve." },
      { name: "values", description: "A list or single value." },
    ],
    minArgs: 2,
    maxArgs: 2,
    docUrl: `${BASE_DOC_URL}/dtl-functions-lists.html`,
  },
  {
    name: "count",
    category: "Lists",
    kind: "expression",
    signature: "count(list)",
    description: "Returns the number of elements in the list.",
    params: [{ name: "list", description: "A list value." }],
    minArgs: 1,
    maxArgs: 1,
    docUrl: `${BASE_DOC_URL}/dtl-functions-lists.html`,
  },
  {
    name: "distinct",
    category: "Lists",
    kind: "expression",
    signature: "distinct([function], values)",
    description:
      "Returns a list of distinct values with duplicates removed. If FUNCTION is given it is evaluated for each value and its return value is used for the duplicate check — the original value is still what is returned. For duplicates the first value wins.",
    params: [
      {
        name: "function",
        description: 'Optional key function for duplicate detection ("_." = current value).',
        optional: true,
      },
      { name: "values", description: "A list value." },
    ],
    minArgs: 1,
    maxArgs: 2,
    docUrl: `${BASE_DOC_URL}/dtl-functions-lists.html`,
  },
  {
    name: "flatten",
    category: "Lists",
    kind: "expression",
    signature: "flatten(list)",
    description: "Flattens one level of nested lists into a single list.",
    params: [{ name: "list", description: "A list that may contain nested lists." }],
    minArgs: 1,
    maxArgs: 1,
    docUrl: `${BASE_DOC_URL}/dtl-functions-lists.html`,
  },
  {
    name: "combine",
    category: "Lists",
    kind: "expression",
    signature: "combine(list, ...)",
    description: "Concatenates multiple lists into one.",
    params: [{ name: "list", description: "One or more lists to combine." }],
    minArgs: 1,
    maxArgs: null,
    docUrl: `${BASE_DOC_URL}/dtl-functions-lists.html`,
  },
  {
    name: "group",
    category: "Lists",
    kind: "expression",
    signature: "group(key-fn, value-fn, values)",
    description:
      "Groups the items in VALUES by executing KEY_FN on each item to produce a group key and VALUE_FN to produce the grouped value. Returns a list of [group-key, grouped-values] tuples, where grouped-values is a list of all values sharing that key.",
    params: [
      { name: "key-fn", description: 'Expression producing the group key ("_." = current item).' },
      {
        name: "value-fn",
        description: 'Expression producing the value to group ("_." = current item).',
      },
      { name: "values", description: "A list to group." },
    ],
    minArgs: 3,
    maxArgs: 3,
    docUrl: `${BASE_DOC_URL}/dtl-functions-lists.html`,
  },
  {
    name: "group-by",
    category: "Lists",
    kind: "expression",
    signature: "group-by([key-fn], [string-fn], values)",
    description:
      "Groups the values in VALUES by the result of KEY_FN. Returns a dictionary where each key is the (transit-encoded JSON) group key and the value is the list of items in that group. If STRING_FN is provided it replaces the default transit-encoding for key generation. KEY_FN and STRING_FN are both optional.",
    params: [
      {
        name: "key-fn",
        description: 'Optional expression producing the group key ("_." = current item).',
        optional: true,
      },
      {
        name: "string-fn",
        description: "Optional expression to produce the string key instead of transit-encoding.",
        optional: true,
      },
      { name: "values", description: "A list to group." },
    ],
    minArgs: 1,
    maxArgs: 3,
    docUrl: `${BASE_DOC_URL}/dtl-functions-lists.html`,
  },
  {
    name: "sorted",
    category: "Lists",
    kind: "expression",
    signature: "sorted([function], values)",
    description:
      'Returns VALUES sorted in ascending order. If FUNCTION is given it is evaluated for each element to produce the sort key; the original value is returned. Does not remove duplicates (use "distinct" for that). Non-list values are returned as-is. Mixed types are ordered using Sesam mixed-type ordering.',
    params: [
      {
        name: "function",
        description: 'Optional sort-key expression ("_." = current element).',
        optional: true,
      },
      { name: "values", description: "A list to sort." },
    ],
    minArgs: 1,
    maxArgs: 2,
    docUrl: `${BASE_DOC_URL}/dtl-functions-lists.html`,
  },
  {
    name: "sorted-descending",
    category: "Lists",
    kind: "expression",
    signature: "sorted-descending([function], values)",
    description:
      "Returns VALUES sorted in descending order. If FUNCTION is given it is evaluated for each element to produce the sort key; the original value is returned. Does not remove duplicates. Non-list values are returned as-is.",
    params: [
      {
        name: "function",
        description: 'Optional sort-key expression ("_." = current element).',
        optional: true,
      },
      { name: "values", description: "A list to sort." },
    ],
    minArgs: 1,
    maxArgs: 2,
    docUrl: `${BASE_DOC_URL}/dtl-functions-lists.html`,
  },
  {
    name: "reversed",
    category: "Lists",
    kind: "expression",
    signature: "reversed(list)",
    description: "Returns the list in reversed order.",
    params: [{ name: "list", description: "A list to reverse." }],
    minArgs: 1,
    maxArgs: 1,
    docUrl: `${BASE_DOC_URL}/dtl-functions-lists.html`,
  },
  {
    name: "slice",
    category: "Lists",
    kind: "expression",
    signature: "slice(start, [end], [stride], values)",
    description:
      "Returns a slice of VALUES from START to END (exclusive) using STRIDE as the step. END defaults to the end of the list; STRIDE defaults to 1. Negative indices count from the end.",
    params: [
      { name: "start", description: "Start index (zero-based; negative counts from end)." },
      {
        name: "end",
        description: "End index (exclusive; omit to go to end of list).",
        optional: true,
      },
      { name: "stride", description: "Step between elements (default 1).", optional: true },
      { name: "values", description: "A list to slice." },
    ],
    minArgs: 2,
    maxArgs: 4,
    docUrl: `${BASE_DOC_URL}/dtl-functions-lists.html`,
  },
  {
    name: "range",
    category: "Lists",
    kind: "expression",
    signature: "range(start, stop [, step])",
    description:
      "Returns a list of integers from START (inclusive) to STOP (exclusive) in STEP increments. STEP defaults to 1 and must not be 0. All arguments must be integers.",
    params: [
      { name: "start", description: "Start value (inclusive)." },
      { name: "stop", description: "End value (exclusive)." },
      { name: "step", description: "Increment (default 1; may be negative).", optional: true },
    ],
    minArgs: 2,
    maxArgs: 3,
    docUrl: `${BASE_DOC_URL}/dtl-functions-lists.html`,
  },
  {
    name: "in",
    category: "Lists",
    kind: "expression",
    signature: "in(values, items)",
    description:
      "Returns true if all values in VALUES exist in ITEMS, i.e. VALUES is a subset of ITEMS. Returns false if VALUES is null or empty.",
    params: [
      { name: "values", description: "Value or list of values to look for." },
      { name: "items", description: "The collection to search within." },
    ],
    minArgs: 2,
    maxArgs: 2,
    docUrl: `${BASE_DOC_URL}/dtl-functions-lists.html`,
  },
  {
    name: "insert",
    category: "Lists",
    kind: "expression",
    signature: "insert(index, values, object)",
    description:
      "Inserts OBJECT at INDEX in VALUES. A negative INDEX counts from the end of the list.",
    params: [
      { name: "index", description: "Insertion position (zero-based; negative counts from end)." },
      { name: "values", description: "The target list." },
      { name: "object", description: "The value to insert." },
    ],
    minArgs: 3,
    maxArgs: 3,
    docUrl: `${BASE_DOC_URL}/dtl-functions-lists.html`,
  },
  {
    name: "enumerate",
    category: "Lists",
    kind: "expression",
    signature: "enumerate([start], values)",
    description:
      'Enumerates VALUES by returning a list of dictionaries with "key" (the counter) and "value" (the element) keys. The counter starts at START (default 0) and increments by 1.',
    params: [
      { name: "start", description: "Optional integer start value (default 0).", optional: true },
      { name: "values", description: "A list to enumerate." },
    ],
    minArgs: 1,
    maxArgs: 2,
    docUrl: `${BASE_DOC_URL}/dtl-functions-lists.html`,
  },
  {
    name: "is-list",
    category: "Lists",
    kind: "expression",
    signature: "is-list(value)",
    description: "Returns true if value is a list.",
    params: [{ name: "value", description: "The value to test." }],
    minArgs: 1,
    maxArgs: 1,
    docUrl: `${BASE_DOC_URL}/dtl-functions-lists.html`,
  },
  {
    name: "is-empty",
    category: "Lists",
    kind: "expression",
    signature: "is-empty(list)",
    description: "Returns true if the list is null or empty.",
    params: [{ name: "list", description: "The list to test." }],
    minArgs: 1,
    maxArgs: 1,
    docUrl: `${BASE_DOC_URL}/dtl-functions-lists.html`,
  },
  {
    name: "is-not-empty",
    category: "Lists",
    kind: "expression",
    signature: "is-not-empty(list)",
    description: "Returns true if the list is non-null and non-empty.",
    params: [{ name: "list", description: "The list to test." }],
    minArgs: 1,
    maxArgs: 1,
    docUrl: `${BASE_DOC_URL}/dtl-functions-lists.html`,
  },
  {
    name: "sum",
    category: "Lists",
    kind: "expression",
    signature: "sum(list)",
    description: "Returns the sum of all numeric elements in the list.",
    params: [{ name: "list", description: "A list of numbers." }],
    minArgs: 1,
    maxArgs: 1,
    docUrl: `${BASE_DOC_URL}/dtl-functions-lists.html`,
  },
  {
    name: "min",
    category: "Lists",
    kind: "expression",
    signature: "min([function], values)",
    description:
      "Returns the minimum value in VALUES. If FUNCTION is given it is evaluated for each element for ordering purposes, but the original value is returned. Mixed types use Sesam mixed-type ordering.",
    params: [
      {
        name: "function",
        description: 'Optional ordering expression ("_." = current element).',
        optional: true,
      },
      { name: "values", description: "A list of values." },
    ],
    minArgs: 1,
    maxArgs: 2,
    docUrl: `${BASE_DOC_URL}/dtl-functions-lists.html`,
  },
  {
    name: "max",
    category: "Lists",
    kind: "expression",
    signature: "max([function], values)",
    description:
      "Returns the maximum value in VALUES. If FUNCTION is given it is evaluated for each element for ordering purposes, but the original value is returned. Mixed types use Sesam mixed-type ordering.",
    params: [
      {
        name: "function",
        description: 'Optional ordering expression ("_." = current element).',
        optional: true,
      },
      { name: "values", description: "A list of values." },
    ],
    minArgs: 1,
    maxArgs: 2,
    docUrl: `${BASE_DOC_URL}/dtl-functions-lists.html`,
  },
] as const satisfies readonly DtlFunction[];

const MathFns = [
  // ─── MATH ────────────────────────────────────────────────────────────────
  {
    name: "+",
    category: "Math",
    kind: "expression",
    signature: "+(a, b, ...)",
    description: "Adds numbers together.",
    params: [{ name: "values", description: "Numeric values to add." }],
    minArgs: 2,
    maxArgs: null,
    docUrl: `${BASE_DOC_URL}/dtl-functions-math.html`,
  },
  {
    name: "-",
    category: "Math",
    kind: "expression",
    signature: "-(a, b)",
    description: "Subtracts b from a.",
    params: [
      { name: "a", description: "Minuend." },
      { name: "b", description: "Subtrahend." },
    ],
    minArgs: 1,
    maxArgs: 2,
    docUrl: `${BASE_DOC_URL}/dtl-functions-math.html`,
  },
  {
    name: "*",
    category: "Math",
    kind: "expression",
    signature: "*(a, b, ...)",
    description: "Multiplies numbers.",
    params: [{ name: "values", description: "Numeric values to multiply." }],
    minArgs: 2,
    maxArgs: null,
    docUrl: `${BASE_DOC_URL}/dtl-functions-math.html`,
  },
  {
    name: "/",
    category: "Math",
    kind: "expression",
    signature: "/(a, b)",
    description: "Divides a by b.",
    params: [
      { name: "a", description: "Numerator." },
      { name: "b", description: "Denominator." },
    ],
    minArgs: 2,
    maxArgs: 2,
    docUrl: `${BASE_DOC_URL}/dtl-functions-math.html`,
  },
  {
    name: "%",
    category: "Math",
    kind: "expression",
    signature: "%(a, b)",
    description: "Returns a modulo b.",
    params: [
      { name: "a", description: "Dividend." },
      { name: "b", description: "Divisor." },
    ],
    minArgs: 2,
    maxArgs: 2,
    docUrl: `${BASE_DOC_URL}/dtl-functions-math.html`,
  },
  {
    name: "^",
    category: "Math",
    kind: "expression",
    signature: "^(base, exponent)",
    description: "Returns base raised to the power of exponent.",
    params: [
      { name: "base", description: "Base number." },
      { name: "exponent", description: "Exponent." },
    ],
    minArgs: 2,
    maxArgs: 2,
    docUrl: `${BASE_DOC_URL}/dtl-functions-math.html`,
  },
  {
    name: "abs",
    category: "Math",
    kind: "expression",
    signature: "abs(value)",
    description: "Returns the absolute value.",
    params: [{ name: "value", description: "A number." }],
    minArgs: 1,
    maxArgs: 1,
    docUrl: `${BASE_DOC_URL}/dtl-functions-math.html`,
  },
  {
    name: "ceil",
    category: "Math",
    kind: "expression",
    signature: "ceil(value)",
    description: "Returns the ceiling (round up) of the value.",
    params: [{ name: "value", description: "A number." }],
    minArgs: 1,
    maxArgs: 1,
    docUrl: `${BASE_DOC_URL}/dtl-functions-math.html`,
  },
  {
    name: "floor",
    category: "Math",
    kind: "expression",
    signature: "floor(value)",
    description: "Returns the floor (round down) of the value.",
    params: [{ name: "value", description: "A number." }],
    minArgs: 1,
    maxArgs: 1,
    docUrl: `${BASE_DOC_URL}/dtl-functions-math.html`,
  },
  {
    name: "round",
    category: "Math",
    kind: "expression",
    signature: "round(value [, ndigits])",
    description: "Rounds value to the given number of decimal digits.",
    params: [
      { name: "value", description: "A number." },
      {
        name: "ndigits",
        description: "Number of decimal places (default 0).",
        optional: true,
      },
    ],
    minArgs: 1,
    maxArgs: 2,
    docUrl: `${BASE_DOC_URL}/dtl-functions-math.html`,
  },
  {
    name: "sqrt",
    category: "Math",
    kind: "expression",
    signature: "sqrt(value)",
    description: "Returns the square root of value.",
    params: [{ name: "value", description: "A non-negative number." }],
    minArgs: 1,
    maxArgs: 1,
    docUrl: `${BASE_DOC_URL}/dtl-functions-math.html`,
  },
  {
    name: "pow",
    category: "Math",
    kind: "expression",
    signature: "pow(base, exponent)",
    description: "Returns base raised to exponent (alias of ^).",
    params: [
      { name: "base", description: "Base number." },
      { name: "exponent", description: "Exponent." },
    ],
    minArgs: 2,
    maxArgs: 2,
    docUrl: `${BASE_DOC_URL}/dtl-functions-math.html`,
  },
  {
    name: "cos",
    category: "Math",
    kind: "expression",
    signature: "cos(radians)",
    description: "Cosine.",
    params: [{ name: "radians", description: "Angle in radians." }],
    minArgs: 1,
    maxArgs: 1,
    docUrl: `${BASE_DOC_URL}/dtl-functions-math.html`,
  },
  {
    name: "sin",
    category: "Math",
    kind: "expression",
    signature: "sin(radians)",
    description: "Sine.",
    params: [{ name: "radians", description: "Angle in radians." }],
    minArgs: 1,
    maxArgs: 1,
    docUrl: `${BASE_DOC_URL}/dtl-functions-math.html`,
  },
  {
    name: "tan",
    category: "Math",
    kind: "expression",
    signature: "tan(radians)",
    description: "Tangent.",
    params: [{ name: "radians", description: "Angle in radians." }],
    minArgs: 1,
    maxArgs: 1,
    docUrl: `${BASE_DOC_URL}/dtl-functions-math.html`,
  },
] as const satisfies readonly DtlFunction[];

const MiscFns = [
  // ─── MISC ────────────────────────────────────────────────────────────────
  {
    name: "hash128",
    category: "Misc",
    kind: "expression",
    signature: "hash128(value)",
    description: "Returns a 128-bit hash of the value as a hex string.",
    params: [{ name: "value", description: "The value to hash." }],
    minArgs: 1,
    maxArgs: 1,
    docUrl: `${BASE_DOC_URL}/dtl-functions-misc.html`,
  },
  {
    name: "literal",
    category: "Misc",
    kind: "expression",
    signature: "literal(value)",
    description: "Returns value as a literal (prevents further evaluation).",
    params: [{ name: "value", description: "A literal value." }],
    minArgs: 1,
    maxArgs: 1,
    docUrl: `${BASE_DOC_URL}/dtl-functions-misc.html`,
  },
  {
    name: "tuples",
    category: "Misc",
    kind: "expression",
    signature: "tuples(list1, list2)",
    description: "Zips two lists into a list of [a, b] pairs.",
    params: [
      { name: "list1", description: "First list." },
      { name: "list2", description: "Second list." },
    ],
    minArgs: 2,
    maxArgs: 2,
    docUrl: `${BASE_DOC_URL}/dtl-functions-misc.html`,
  },
  {
    name: "completeness",
    category: "Misc",
    kind: "expression",
    signature: "completeness(value)",
    description: "Returns a completeness score for value (fraction of non-null leaf values).",
    params: [{ name: "value", description: "A dict or entity." }],
    minArgs: 1,
    maxArgs: 1,
    docUrl: `${BASE_DOC_URL}/dtl-functions-misc.html`,
  },
  {
    name: "is-changed",
    category: "Misc",
    kind: "expression",
    signature: "is-changed(property)",
    description: "Returns true if the source property value differs from the previous version.",
    params: [{ name: "property", description: "A property path expression." }],
    minArgs: 1,
    maxArgs: 1,
    docUrl: `${BASE_DOC_URL}/dtl-functions-misc.html`,
  },
] as const satisfies readonly DtlFunction[];

const NiFns = [
  // ─── NAMESPACED IDENTIFIERS ──────────────────────────────────────────────
  {
    name: "ni",
    category: "Namespaced identifiers",
    kind: "expression",
    signature: "ni([namespace], value)",
    description:
      "Translates input values to namespaced identifiers. NAMESPACE is optional; when omitted the global namespace is used. Strings and URIs in VALUE are cast to NIs. URIs (without a NAMESPACE) are collapsed: the URI prefix is looked up in declared namespaces, or a generated namespace is created.",
    params: [
      {
        name: "namespace",
        description: "Optional namespace string. Omit to use the global namespace.",
      },
      { name: "value", description: "String, URI, NI, or list of values to convert." },
    ],
    minArgs: 1,
    maxArgs: 2,
    docUrl: `${BASE_DOC_URL}/dtl-functions-namespaced-identifiers.html`,
  },
  {
    name: "ni-id",
    category: "Namespaced identifiers",
    kind: "expression",
    signature: "ni-id(value)",
    description:
      'Extracts the local id part of a namespaced identifier. The NI syntax "~:ns:id" and the shorthand string "ns:id" are both supported. Non-NI and non-string values are ignored. Operates element-wise over lists.',
    params: [{ name: "value", description: "A namespaced identifier, string, or list thereof." }],
    minArgs: 1,
    maxArgs: 1,
    docUrl: `${BASE_DOC_URL}/dtl-functions-namespaced-identifiers.html`,
  },
  {
    name: "ni-ns",
    category: "Namespaced identifiers",
    kind: "expression",
    signature: "ni-ns(value)",
    description:
      'Extracts the namespace part of a namespaced identifier. The NI syntax "~:ns:id" and the shorthand string "ns:id" are both supported. Returns an empty string for bare identifiers with no namespace. Non-NI and non-string values are ignored. Operates element-wise over lists.',
    params: [{ name: "value", description: "A namespaced identifier, string, or list thereof." }],
    minArgs: 1,
    maxArgs: 1,
    docUrl: `${BASE_DOC_URL}/dtl-functions-namespaced-identifiers.html`,
  },
  {
    name: "is-ni",
    category: "Namespaced identifiers",
    kind: "expression",
    signature: "is-ni(value)",
    description:
      "Returns true if value is a namespaced identifier literal. If value is a list, returns true when the first element of the list is a namespaced identifier.",
    params: [{ name: "value", description: "The value or list to test." }],
    minArgs: 1,
    maxArgs: 1,
    docUrl: `${BASE_DOC_URL}/dtl-functions-namespaced-identifiers.html`,
  },
  {
    name: "ni-collapse",
    category: "Namespaced identifiers",
    kind: "expression",
    signature: "ni-collapse(values)",
    description:
      "Deprecated. Uses the namespaces.default service metadata to produce a namespaced identifier from URLs. Non-URL values are ignored. Requires the global_defaults.symmetric_namespace_collapse option.",
    params: [
      {
        name: "values",
        description: "One or more URL strings or URI parameters to collapse into NIs.",
      },
    ],
    minArgs: 1,
    maxArgs: null,
    docUrl: "https://docs.sesam.io/hub/deprecations.html#ni-collapse",
  },
  {
    name: "ni-expand",
    category: "Namespaced identifiers",
    kind: "expression",
    signature: "ni-expand(values)",
    description:
      "Deprecated. Uses the namespaces.default service metadata to produce a URL string from a namespaced identifier. Non-NI values are ignored. Requires the global_defaults.symmetric_namespace_collapse option.",
    params: [
      {
        name: "values",
        description: "One or more namespaced identifiers to expand into URLs.",
      },
    ],
    minArgs: 1,
    maxArgs: null,
    docUrl: "https://docs.sesam.io/hub/deprecations.html#ni-expand",
  },
] as const satisfies readonly DtlFunction[];

const NullFns = [
  // ─── NULLS ───────────────────────────────────────────────────────────────
  {
    name: "is-null",
    category: "Nulls",
    kind: "expression",
    signature: "is-null(value)",
    description: "Returns true if value is null.",
    params: [{ name: "value", description: "The value to test." }],
    minArgs: 1,
    maxArgs: 1,
    docUrl: `${BASE_DOC_URL}/dtl-functions-nulls.html`,
  },
  {
    name: "is-not-null",
    category: "Nulls",
    kind: "expression",
    signature: "is-not-null(value)",
    description: "Returns true if value is not null.",
    params: [{ name: "value", description: "The value to test." }],
    minArgs: 1,
    maxArgs: 1,
    docUrl: `${BASE_DOC_URL}/dtl-functions-nulls.html`,
  },
  {
    name: "if-null",
    category: "Nulls",
    kind: "expression",
    signature: "if-null(value, default)",
    description: "Returns value if non-null, otherwise returns default.",
    params: [
      { name: "value", description: "The value to check." },
      { name: "default", description: "Fallback value when null." },
    ],
    minArgs: 2,
    maxArgs: 2,
    docUrl: `${BASE_DOC_URL}/dtl-functions-nulls.html`,
  },
] as const satisfies readonly DtlFunction[];

const NumberFns = [
  // ─── NUMBERS ─────────────────────────────────────────────────────────────
  {
    name: "integer",
    category: "Numbers",
    kind: "expression",
    signature: "integer(value)",
    description: "Converts value to an integer.",
    params: [{ name: "value", description: "The value to convert." }],
    minArgs: 1,
    maxArgs: 1,
    docUrl: `${BASE_DOC_URL}/dtl-functions-numbers.html`,
  },
  {
    name: "float",
    category: "Numbers",
    kind: "expression",
    signature: "float(value)",
    description: "Converts value to a float.",
    params: [{ name: "value", description: "The value to convert." }],
    minArgs: 1,
    maxArgs: 1,
    docUrl: `${BASE_DOC_URL}/dtl-functions-numbers.html`,
  },
  {
    name: "decimal",
    category: "Numbers",
    kind: "expression",
    signature: "decimal(value)",
    description: "Converts value to a decimal.",
    params: [{ name: "value", description: "The value to convert." }],
    minArgs: 1,
    maxArgs: 1,
    docUrl: `${BASE_DOC_URL}/dtl-functions-numbers.html`,
  },
  {
    name: "hex",
    category: "Numbers",
    kind: "expression",
    signature: "hex(value)",
    description: "Returns a hexadecimal string representation of an integer.",
    params: [{ name: "value", description: "An integer." }],
    minArgs: 1,
    maxArgs: 1,
    docUrl: `${BASE_DOC_URL}/dtl-functions-numbers.html`,
  },
  {
    name: "is-integer",
    category: "Numbers",
    kind: "expression",
    signature: "is-integer(value)",
    description: "Returns true if value is an integer.",
    params: [{ name: "value", description: "The value to test." }],
    minArgs: 1,
    maxArgs: 1,
    docUrl: `${BASE_DOC_URL}/dtl-functions-numbers.html`,
  },
  {
    name: "is-float",
    category: "Numbers",
    kind: "expression",
    signature: "is-float(value)",
    description: "Returns true if value is a float.",
    params: [{ name: "value", description: "The value to test." }],
    minArgs: 1,
    maxArgs: 1,
    docUrl: `${BASE_DOC_URL}/dtl-functions-numbers.html`,
  },
  {
    name: "is-decimal",
    category: "Numbers",
    kind: "expression",
    signature: "is-decimal(value)",
    description: "Returns true if value is a decimal.",
    params: [{ name: "value", description: "The value to test." }],
    minArgs: 1,
    maxArgs: 1,
    docUrl: `${BASE_DOC_URL}/dtl-functions-numbers.html`,
  },
] as const satisfies readonly DtlFunction[];

const PhonenumberFns = [
  // ─── PHONENUMBERS ────────────────────────────────────────────────────────
  {
    name: "phonenumber-parse",
    category: "Phonenumbers",
    kind: "expression",
    signature: "phonenumber-parse(number [, region])",
    description: "Parses a phone number string into a structured dict.",
    params: [
      { name: "number", description: "Phone number string." },
      { name: "region", description: "ISO country code hint.", optional: true },
    ],
    minArgs: 1,
    maxArgs: 2,
    docUrl: `${BASE_DOC_URL}/dtl-functions-phonenumbers.html`,
  },
  {
    name: "phonenumber-format",
    category: "Phonenumbers",
    kind: "expression",
    signature: "phonenumber-format(format, phonenumber)",
    description: "Formats a parsed phone number into a string.",
    params: [
      {
        name: "format",
        description: '"E164", "INTERNATIONAL", "NATIONAL", "RFC3966".',
      },
      { name: "phonenumber", description: "Parsed phone number dict." },
    ],
    minArgs: 2,
    maxArgs: 2,
    docUrl: `${BASE_DOC_URL}/dtl-functions-phonenumbers.html`,
  },
] as const satisfies readonly DtlFunction[];

const SetFns = [
  // ─── SETS ────────────────────────────────────────────────────────────────
  {
    name: "union",
    category: "Sets",
    kind: "expression",
    signature: "union(set1, set2)",
    description: "Returns the union of two sets (lists).",
    params: [
      { name: "set1", description: "First set." },
      { name: "set2", description: "Second set." },
    ],
    minArgs: 2,
    maxArgs: 2,
    docUrl: `${BASE_DOC_URL}/dtl-functions-sets.html`,
  },
  {
    name: "intersection",
    category: "Sets",
    kind: "expression",
    signature: "intersection(set1, set2)",
    description: "Returns the intersection of two sets.",
    params: [
      { name: "set1", description: "First set." },
      { name: "set2", description: "Second set." },
    ],
    minArgs: 2,
    maxArgs: 2,
    docUrl: `${BASE_DOC_URL}/dtl-functions-sets.html`,
  },
  {
    name: "difference",
    category: "Sets",
    kind: "expression",
    signature: "difference(set1, set2)",
    description: "Returns elements in set1 not present in set2.",
    params: [
      { name: "set1", description: "First set." },
      { name: "set2", description: "Second set." },
    ],
    minArgs: 2,
    maxArgs: 2,
    docUrl: `${BASE_DOC_URL}/dtl-functions-sets.html`,
  },
  {
    name: "intersects",
    category: "Sets",
    kind: "expression",
    signature: "intersects(set1, set2)",
    description: "Returns true if the two sets share at least one element.",
    params: [
      { name: "set1", description: "First set." },
      { name: "set2", description: "Second set." },
    ],
    minArgs: 2,
    maxArgs: 2,
    docUrl: `${BASE_DOC_URL}/dtl-functions-sets.html`,
  },
] as const satisfies readonly DtlFunction[];

const StringFns = [
  // ─── STRINGS ─────────────────────────────────────────────────────────────
  {
    name: "concat",
    category: "Strings",
    kind: "expression",
    signature: "concat(value, ...)",
    description: "Concatenates values into a single string.",
    params: [{ name: "value", description: "One or more values to concatenate." }],
    minArgs: 1,
    maxArgs: null,
    docUrl: `${BASE_DOC_URL}/dtl-functions-strings.html`,
  },
  {
    name: "join",
    category: "Strings",
    kind: "expression",
    signature: "join(separator, list)",
    description: "Joins list elements into a string with separator.",
    params: [
      { name: "separator", description: "String separator." },
      { name: "list", description: "A list of values to join." },
    ],
    minArgs: 2,
    maxArgs: 2,
    docUrl: `${BASE_DOC_URL}/dtl-functions-strings.html`,
  },
  {
    name: "split",
    category: "Strings",
    kind: "expression",
    signature: "split(separator, string)",
    description: "Splits string by separator into a list.",
    params: [
      { name: "separator", description: "Delimiter string." },
      { name: "string", description: "The string to split." },
    ],
    minArgs: 2,
    maxArgs: 2,
    docUrl: `${BASE_DOC_URL}/dtl-functions-strings.html`,
  },
  {
    name: "upper",
    category: "Strings",
    kind: "expression",
    signature: "upper(string)",
    description: "Converts string to upper case.",
    params: [{ name: "string", description: "A string." }],
    minArgs: 1,
    maxArgs: 1,
    docUrl: `${BASE_DOC_URL}/dtl-functions-strings.html`,
  },
  {
    name: "lower",
    category: "Strings",
    kind: "expression",
    signature: "lower(string)",
    description: "Converts string to lower case.",
    params: [{ name: "string", description: "A string." }],
    minArgs: 1,
    maxArgs: 1,
    docUrl: `${BASE_DOC_URL}/dtl-functions-strings.html`,
  },
  {
    name: "strip",
    category: "Strings",
    kind: "expression",
    signature: "strip(string)",
    description: "Removes leading and trailing whitespace.",
    params: [{ name: "string", description: "A string." }],
    minArgs: 1,
    maxArgs: 1,
    docUrl: `${BASE_DOC_URL}/dtl-functions-strings.html`,
  },
  {
    name: "lstrip",
    category: "Strings",
    kind: "expression",
    signature: "lstrip(string)",
    description: "Removes leading whitespace.",
    params: [{ name: "string", description: "A string." }],
    minArgs: 1,
    maxArgs: 1,
    docUrl: `${BASE_DOC_URL}/dtl-functions-strings.html`,
  },
  {
    name: "rstrip",
    category: "Strings",
    kind: "expression",
    signature: "rstrip(string)",
    description: "Removes trailing whitespace.",
    params: [{ name: "string", description: "A string." }],
    minArgs: 1,
    maxArgs: 1,
    docUrl: `${BASE_DOC_URL}/dtl-functions-strings.html`,
  },
  {
    name: "replace",
    category: "Strings",
    kind: "expression",
    signature: "replace(search, replacement, string)",
    description: "Replaces all occurrences of search with replacement in string.",
    params: [
      { name: "search", description: "String to find." },
      { name: "replacement", description: "Replacement string." },
      { name: "string", description: "The string to process." },
    ],
    minArgs: 3,
    maxArgs: 3,
    docUrl: `${BASE_DOC_URL}/dtl-functions-strings.html`,
  },
  {
    name: "substring",
    category: "Strings",
    kind: "expression",
    signature: "substring(string, start [, end])",
    description: "Returns a substring from start to end.",
    params: [
      { name: "string", description: "A string." },
      { name: "start", description: "Start index." },
      { name: "end", description: "End index (exclusive).", optional: true },
    ],
    minArgs: 2,
    maxArgs: 3,
    docUrl: `${BASE_DOC_URL}/dtl-functions-strings.html`,
  },
  {
    name: "length",
    category: "Strings",
    kind: "expression",
    signature: "length(string)",
    description: "Returns the character length of the string.",
    params: [{ name: "string", description: "A string." }],
    minArgs: 1,
    maxArgs: 1,
    docUrl: `${BASE_DOC_URL}/dtl-functions-strings.html`,
  },
  {
    name: "matches",
    category: "Strings",
    kind: "expression",
    signature: "matches(pattern, string)",
    description: "Returns true if string matches the regex pattern.",
    params: [
      { name: "pattern", description: "A regex pattern string." },
      { name: "string", description: "The string to test." },
    ],
    minArgs: 2,
    maxArgs: 2,
    docUrl: `${BASE_DOC_URL}/dtl-functions-strings.html`,
  },
  {
    name: "string",
    category: "Strings",
    kind: "expression",
    signature: "string(value)",
    description: "Converts value to a string.",
    params: [{ name: "value", description: "The value to convert." }],
    minArgs: 1,
    maxArgs: 1,
    docUrl: `${BASE_DOC_URL}/dtl-functions-strings.html`,
  },
  {
    name: "is-string",
    category: "Strings",
    kind: "expression",
    signature: "is-string(value)",
    description: "Returns true if value is a string.",
    params: [{ name: "value", description: "The value to test." }],
    minArgs: 1,
    maxArgs: 1,
    docUrl: `${BASE_DOC_URL}/dtl-functions-strings.html`,
  },
  {
    name: "ljust",
    category: "Strings",
    kind: "expression",
    signature: "ljust(string, width [, fill])",
    description: "Left-justifies string within a field of given width.",
    params: [
      { name: "string", description: "String to pad." },
      { name: "width", description: "Total width." },
      {
        name: "fill",
        description: "Fill character (default space).",
        optional: true,
      },
    ],
    minArgs: 2,
    maxArgs: 3,
    docUrl: `${BASE_DOC_URL}/dtl-functions-strings.html`,
  },
  {
    name: "rjust",
    category: "Strings",
    kind: "expression",
    signature: "rjust(string, width [, fill])",
    description: "Right-justifies string within a field of given width.",
    params: [
      { name: "string", description: "String to pad." },
      { name: "width", description: "Total width." },
      {
        name: "fill",
        description: "Fill character (default space).",
        optional: true,
      },
    ],
    minArgs: 2,
    maxArgs: 3,
    docUrl: `${BASE_DOC_URL}/dtl-functions-strings.html`,
  },
] as const satisfies readonly DtlFunction[];

const UriFns = [
  // ─── URIs ────────────────────────────────────────────────────────────────
  {
    name: "uri",
    category: "URIs",
    kind: "expression",
    signature: "uri(value)",
    description: "Creates a URI from value.",
    params: [{ name: "value", description: "A URI string." }],
    minArgs: 1,
    maxArgs: 1,
    docUrl: `${BASE_DOC_URL}/dtl-functions-uris.html`,
  },
  {
    name: "is-uri",
    category: "URIs",
    kind: "expression",
    signature: "is-uri(value)",
    description: "Returns true if value is a URI.",
    params: [{ name: "value", description: "The value to test." }],
    minArgs: 1,
    maxArgs: 1,
    docUrl: `${BASE_DOC_URL}/dtl-functions-uris.html`,
  },
  {
    name: "url-quote",
    category: "URIs",
    kind: "expression",
    signature: "url-quote(string)",
    description: "URL-encodes the string.",
    params: [{ name: "string", description: "String to encode." }],
    minArgs: 1,
    maxArgs: 1,
    docUrl: `${BASE_DOC_URL}/dtl-functions-uris.html`,
  },
  {
    name: "url-unquote",
    category: "URIs",
    kind: "expression",
    signature: "url-unquote(string)",
    description: "URL-decodes the string.",
    params: [{ name: "string", description: "String to decode." }],
    minArgs: 1,
    maxArgs: 1,
    docUrl: `${BASE_DOC_URL}/dtl-functions-uris.html`,
  },
] as const satisfies readonly DtlFunction[];

const UuidFns = [
  // ─── UUIDs ───────────────────────────────────────────────────────────────
  {
    name: "uuid",
    category: "UUIDs",
    kind: "expression",
    signature: "uuid()",
    description: "Generates a new random UUID string.",
    params: [],
    minArgs: 0,
    maxArgs: 0,
    docUrl: `${BASE_DOC_URL}/dtl-functions-uuids.html`,
  },
  {
    name: "is-uuid",
    category: "UUIDs",
    kind: "expression",
    signature: "is-uuid(value)",
    description: "Returns true if value is a UUID string.",
    params: [{ name: "value", description: "The value to test." }],
    minArgs: 1,
    maxArgs: 1,
    docUrl: `${BASE_DOC_URL}/dtl-functions-uuids.html`,
  },
] as const satisfies readonly DtlFunction[];

// ---------------------------------------------------------------------------
// Combined registry
// ---------------------------------------------------------------------------
const FUNCTIONS: DtlFunction[] = [
  ...TransformFns,
  ...BooleanLogicFns,
  ...BooleanFns,
  ...BytesFns,
  ...ComparisonFns,
  ...ConditionalFns,
  ...DateTimeFns,
  ...DictionaryFns,
  ...EncryptionFns,
  ...HopsFns,
  ...JsonFns,
  ...ListFns,
  ...MathFns,
  ...MiscFns,
  ...NiFns,
  ...NullFns,
  ...NumberFns,
  ...PhonenumberFns,
  ...SetFns,
  ...StringFns,
  ...UriFns,
  ...UuidFns,
];

// ---------------------------------------------------------------------------
// Index for O(1) lookups
// ---------------------------------------------------------------------------
const INDEX = new Map<string, DtlFunction>(FUNCTIONS.map((f) => [f.name, f]));

// ---------------------------------------------------------------------------
// Public API
// ---------------------------------------------------------------------------

/** Returns the definition for the given function name, or undefined if unknown. */
export const getDtlFunction = (name: string): DtlFunction | undefined => INDEX.get(name);

/** Returns all registered DTL functions. */
export const getAllFunctions = (): DtlFunction[] => FUNCTIONS;

/** Returns all transform functions (those with side-effects). */
export const getTransformFunctions = (): DtlFunction[] =>
  FUNCTIONS.filter((f) => f.kind === "transform");

/** Returns all expression functions (no side-effects, return values). */
export const getExpressionFunctions = (): DtlFunction[] =>
  FUNCTIONS.filter((f) => f.kind === "expression");

/** Returns all functions in a given category. */
export const getFunctionsByCategory = (category: DtlCategory): DtlFunction[] =>
  FUNCTIONS.filter((f) => f.category === category);

/** Returns all known function names. */
export const getAllFunctionNames = (): string[] => FUNCTIONS.map((f) => f.name);

/** Returns true if the given name is a known DTL function. */
export const isKnownFunction = (name: string): boolean => INDEX.has(name);

/** Built-in DTL variable descriptions. */
export const DTL_VARIABLES: Record<string, string> = {
  _S: "Source entity — the input entity being processed by the transform.",
  _T: "Target entity — the entity being constructed by the transform.",
  _P: "Parent context — available inside `apply` functions, refers to the parent entity.",
  _R: "Root context — contains both `_S` and `_T`, accessible at any nesting depth.",
  _B: "Request context — holds variables defined by URL parameters in HTTP endpoint sinks.",
  _: "Current value — refers to the current element in functional expressions like `map` and `filter`.",
};

/** Sesam entity reserved fields. */
export const ENTITY_RESERVED_FIELDS = [
  "_id",
  "_deleted",
  "_filtered",
  "_hash",
  "_previous",
  "_tracked",
  "_ts",
  "_updated",
  "$children",
  "$ids",
  "$replaced",
];
