/**
 * DTL Function Registry
 * Single source of truth for all DTL functions used by both the client and the language server.
 * Based on official Sesam DTL documentation: https://docs.sesam.io/hub/data-transformation-language.html
 */

import type {
  DtlCategory,
  DtlFunction,
  DtlFunctionKind,
  DtlParam,
} from "../../types/dtl-registry.types";

export type { DtlCategory, DtlFunction, DtlFunctionKind, DtlParam };

const BASE_DOC_URL = "https://docs.sesam.io/hub/dtl";

// ---------------------------------------------------------------------------
// Registry entries
// ---------------------------------------------------------------------------
const FUNCTIONS: DtlFunction[] = [
  // ─── TRANSFORMS ─────────────────────────────────────────────────────────
  {
    name: "add",
    category: "Transforms",
    kind: "transform",
    signature: "add(property, value)",
    description: "Adds a property with the given value to the target entity.",
    params: [
      {
        name: "property",
        description: "The property name to set on the target entity.",
      },
      { name: "value", description: "The value to assign to the property." },
    ],
    minArgs: 2,
    maxArgs: 2,
    docUrl: `${BASE_DOC_URL}/dtl-functions-transforms.html`,
  },
  {
    name: "add-if",
    category: "Transforms",
    kind: "transform",
    signature: "add-if(property, value)",
    description: "Adds a property to the target entity only if the value is truthy.",
    params: [
      {
        name: "property",
        description: "The property name to set on the target entity.",
      },
      {
        name: "value",
        description: "The value to assign. Property is not set if value is null/false.",
      },
    ],
    minArgs: 2,
    maxArgs: 2,
    docUrl: `${BASE_DOC_URL}/dtl-functions-transforms.html`,
  },
  {
    name: "copy",
    category: "Transforms",
    kind: "transform",
    signature: "copy(property-or-wildcard)",
    description: "Copies one or more properties from the source entity to the target entity.",
    params: [
      {
        name: "property-or-wildcard",
        description: 'Property name or wildcard (e.g. "*").',
      },
    ],
    minArgs: 1,
    maxArgs: 1,
    docUrl: `${BASE_DOC_URL}/dtl-functions-transforms.html`,
  },
  {
    name: "default",
    category: "Transforms",
    kind: "transform",
    signature: "default(property, value)",
    description: "Sets a property on the target entity only if it is not already set.",
    params: [
      { name: "property", description: "The property name." },
      { name: "value", description: "The default value." },
    ],
    minArgs: 2,
    maxArgs: 2,
    docUrl: `${BASE_DOC_URL}/dtl-functions-transforms.html`,
  },
  {
    name: "make-ni",
    category: "Transforms",
    kind: "transform",
    signature: "make-ni(property, namespace, value)",
    description: "Creates a namespaced identifier and adds it to the target entity.",
    params: [
      { name: "property", description: "Target property name." },
      { name: "namespace", description: "Namespace string." },
      { name: "value", description: "Value to namespace." },
    ],
    minArgs: 3,
    maxArgs: 3,
    docUrl: `${BASE_DOC_URL}/dtl-functions-transforms.html`,
  },
  {
    name: "merge",
    category: "Transforms",
    kind: "transform",
    signature: "merge(source)",
    description: "Merges all properties from the given dict/entity into the target entity.",
    params: [
      {
        name: "source",
        description: "A dict or entity whose properties are merged.",
      },
    ],
    minArgs: 1,
    maxArgs: 1,
    docUrl: `${BASE_DOC_URL}/dtl-functions-transforms.html`,
  },
  {
    name: "merge-union",
    category: "Transforms",
    kind: "transform",
    signature: "merge-union(source)",
    description: "Merges properties using union semantics — existing list values are unioned.",
    params: [{ name: "source", description: "A dict or entity." }],
    minArgs: 1,
    maxArgs: 1,
    docUrl: `${BASE_DOC_URL}/dtl-functions-transforms.html`,
  },
  {
    name: "remove",
    category: "Transforms",
    kind: "transform",
    signature: "remove(property-or-wildcard)",
    description: "Removes one or more properties from the target entity.",
    params: [
      {
        name: "property-or-wildcard",
        description: "Property name or wildcard.",
      },
    ],
    minArgs: 1,
    maxArgs: 1,
    docUrl: `${BASE_DOC_URL}/dtl-functions-transforms.html`,
  },
  {
    name: "rename",
    category: "Transforms",
    kind: "transform",
    signature: "rename(new-name, old-name)",
    description: "Copies a property from old-name to new-name on the target entity.",
    params: [
      { name: "new-name", description: "New property name." },
      { name: "old-name", description: "Source property path." },
    ],
    minArgs: 2,
    maxArgs: 2,
    docUrl: `${BASE_DOC_URL}/dtl-functions-transforms.html`,
  },
  {
    name: "create",
    category: "Transforms",
    kind: "transform",
    signature: "create(entity, ...)",
    description: "Creates one or more new root entities in the output stream.",
    params: [{ name: "entity", description: "Entity or list of entities to emit." }],
    minArgs: 1,
    maxArgs: null,
    docUrl: `${BASE_DOC_URL}/dtl-functions-transforms.html`,
  },
  {
    name: "create-child",
    category: "Transforms",
    kind: "transform",
    signature: "create-child(entity, ...)",
    description: "Creates child entities added to the $children field of the target entity.",
    params: [
      {
        name: "entity",
        description: "Entity or list of entities to create as children.",
      },
    ],
    minArgs: 1,
    maxArgs: null,
    docUrl: `${BASE_DOC_URL}/dtl-functions-transforms.html`,
  },
  {
    name: "filter",
    category: "Transforms",
    kind: "transform",
    signature: "filter(condition)",
    description: "Discards the current entity if the condition is falsy.",
    params: [
      {
        name: "condition",
        description: "Boolean expression. Entity is kept when truthy.",
      },
    ],
    minArgs: 1,
    maxArgs: 1,
    docUrl: `${BASE_DOC_URL}/dtl-functions-transforms.html`,
  },
  {
    name: "discard",
    category: "Transforms",
    kind: "transform",
    signature: "discard()",
    description: "Unconditionally discards the current entity from the output stream.",
    params: [],
    minArgs: 0,
    maxArgs: 0,
    docUrl: `${BASE_DOC_URL}/dtl-functions-transforms.html`,
  },
  {
    name: "if",
    category: "Transforms",
    kind: "transform",
    signature: "if(condition, then [, else])",
    description:
      "Conditionally applies a transform: executes `then` when condition is truthy, `else` otherwise.",
    params: [
      { name: "condition", description: "Boolean expression." },
      {
        name: "then",
        description: "Transform to apply when condition is true.",
      },
      {
        name: "else",
        description: "Transform to apply when condition is false.",
        optional: true,
      },
    ],
    minArgs: 2,
    maxArgs: 3,
    docUrl: `${BASE_DOC_URL}/dtl-functions-transforms.html`,
  },
  {
    name: "case",
    category: "Transforms",
    kind: "transform",
    signature: "case([condition, transform, ...] [, default-transform])",
    description: "Evaluates each condition in order and applies the first matching transform.",
    params: [
      {
        name: "...pairs",
        description: "Alternating condition/transform pairs, optional default at end.",
      },
    ],
    minArgs: 1,
    maxArgs: null,
    docUrl: `${BASE_DOC_URL}/dtl-functions-transforms.html`,
  },
  {
    name: "case-eq",
    category: "Transforms",
    kind: "transform",
    signature: "case-eq(value, [match, transform, ...] [, default-transform])",
    description: "Compares value against each match and applies the first matching transform.",
    params: [
      { name: "value", description: "The value to compare." },
      {
        name: "...pairs",
        description: "Alternating match/transform pairs, optional default at end.",
      },
    ],
    minArgs: 2,
    maxArgs: null,
    docUrl: `${BASE_DOC_URL}/dtl-functions-transforms.html`,
  },
  {
    name: "comment",
    category: "Transforms",
    kind: "transform",
    signature: "comment(text)",
    description: "A no-op transform used for inline documentation.",
    params: [{ name: "text", description: "Comment text (ignored at runtime)." }],
    minArgs: 1,
    maxArgs: 1,
    docUrl: `${BASE_DOC_URL}/dtl-functions-transforms.html`,
  },
  {
    name: "fail!",
    category: "Transforms",
    kind: "transform",
    signature: "fail!(message)",
    description: "Raises an error and aborts processing of the current entity.",
    params: [{ name: "message", description: "Error message string." }],
    minArgs: 0,
    maxArgs: 1,
    docUrl: `${BASE_DOC_URL}/dtl-functions-transforms.html`,
  },
  {
    name: "sleep!",
    category: "Transforms",
    kind: "transform",
    signature: "sleep!(milliseconds)",
    description: "Pauses processing for the given number of milliseconds.",
    params: [{ name: "milliseconds", description: "Sleep duration in ms." }],
    minArgs: 1,
    maxArgs: 1,
    docUrl: `${BASE_DOC_URL}/dtl-functions-transforms.html`,
  },
  {
    name: "trip!",
    category: "Transforms",
    kind: "transform",
    signature: "trip!(message)",
    description: "Marks the pump as failed with the given message without discarding the entity.",
    params: [{ name: "message", description: "Error message string." }],
    minArgs: 0,
    maxArgs: 1,
    docUrl: `${BASE_DOC_URL}/dtl-functions-transforms.html`,
  },

  // ─── BOOLEAN LOGIC ───────────────────────────────────────────────────────
  {
    name: "and",
    category: "Boolean logic",
    kind: "expression",
    signature: "and(expr, ...)",
    description: "Returns true if all expressions are truthy.",
    params: [{ name: "expr", description: "One or more boolean expressions." }],
    minArgs: 1,
    maxArgs: null,
    docUrl: `${BASE_DOC_URL}/dtl-functions-boolean-logic.html`,
  },
  {
    name: "or",
    category: "Boolean logic",
    kind: "expression",
    signature: "or(expr, ...)",
    description: "Returns true if at least one expression is truthy.",
    params: [{ name: "expr", description: "One or more boolean expressions." }],
    minArgs: 1,
    maxArgs: null,
    docUrl: `${BASE_DOC_URL}/dtl-functions-boolean-logic.html`,
  },
  {
    name: "not",
    category: "Boolean logic",
    kind: "expression",
    signature: "not(expr)",
    description: "Returns the logical negation of the expression.",
    params: [{ name: "expr", description: "A boolean expression." }],
    minArgs: 1,
    maxArgs: 1,
    docUrl: `${BASE_DOC_URL}/dtl-functions-boolean-logic.html`,
  },
  {
    name: "all",
    category: "Boolean logic",
    kind: "expression",
    signature: "all(list, condition)",
    description: "Returns true if all items in the list satisfy the condition.",
    params: [
      { name: "list", description: "A list to iterate over." },
      { name: "condition", description: "A boolean expression using _." },
    ],
    minArgs: 2,
    maxArgs: 2,
    docUrl: `${BASE_DOC_URL}/dtl-functions-boolean-logic.html`,
  },
  {
    name: "any",
    category: "Boolean logic",
    kind: "expression",
    signature: "any(list, condition)",
    description: "Returns true if any item in the list satisfies the condition.",
    params: [
      { name: "list", description: "A list to iterate over." },
      { name: "condition", description: "A boolean expression using _." },
    ],
    minArgs: 2,
    maxArgs: 2,
    docUrl: `${BASE_DOC_URL}/dtl-functions-boolean-logic.html`,
  },

  // ─── BOOLEANS ────────────────────────────────────────────────────────────
  {
    name: "boolean",
    category: "Booleans",
    kind: "expression",
    signature: "boolean(value)",
    description: "Casts value to a boolean.",
    params: [{ name: "value", description: "The value to cast." }],
    minArgs: 1,
    maxArgs: 1,
    docUrl: `${BASE_DOC_URL}/dtl-functions-booleans.html`,
  },
  {
    name: "is-boolean",
    category: "Booleans",
    kind: "expression",
    signature: "is-boolean(value)",
    description: "Returns true if value is a boolean.",
    params: [{ name: "value", description: "The value to test." }],
    minArgs: 1,
    maxArgs: 1,
    docUrl: `${BASE_DOC_URL}/dtl-functions-booleans.html`,
  },

  // ─── BYTES ───────────────────────────────────────────────────────────────
  {
    name: "base64-encode",
    category: "Bytes",
    kind: "expression",
    signature: "base64-encode(value)",
    description: "Encodes value as a Base64 string.",
    params: [{ name: "value", description: "Bytes or string to encode." }],
    minArgs: 1,
    maxArgs: 1,
    docUrl: `${BASE_DOC_URL}/dtl-functions-bytes.html`,
  },
  {
    name: "base64-decode",
    category: "Bytes",
    kind: "expression",
    signature: "base64-decode(value)",
    description: "Decodes a Base64-encoded string to bytes.",
    params: [{ name: "value", description: "Base64 string to decode." }],
    minArgs: 1,
    maxArgs: 1,
    docUrl: `${BASE_DOC_URL}/dtl-functions-bytes.html`,
  },
  {
    name: "bytes",
    category: "Bytes",
    kind: "expression",
    signature: "bytes(value)",
    description: "Converts a value to bytes.",
    params: [{ name: "value", description: "String or integer list." }],
    minArgs: 1,
    maxArgs: 1,
    docUrl: `${BASE_DOC_URL}/dtl-functions-bytes.html`,
  },
  {
    name: "is-bytes",
    category: "Bytes",
    kind: "expression",
    signature: "is-bytes(value)",
    description: "Returns true if value is a bytes object.",
    params: [{ name: "value", description: "The value to test." }],
    minArgs: 1,
    maxArgs: 1,
    docUrl: `${BASE_DOC_URL}/dtl-functions-bytes.html`,
  },

  // ─── COMPARISONS ─────────────────────────────────────────────────────────
  {
    name: "eq",
    category: "Comparisons",
    kind: "expression",
    signature: "eq(a, b)",
    description: "Returns true if a equals b.",
    params: [
      { name: "a", description: "Left operand." },
      { name: "b", description: "Right operand." },
    ],
    minArgs: 2,
    maxArgs: 2,
    docUrl: `${BASE_DOC_URL}/dtl-functions-comparisons.html`,
  },
  {
    name: "neq",
    category: "Comparisons",
    kind: "expression",
    signature: "neq(a, b)",
    description: "Returns true if a is not equal to b.",
    params: [
      { name: "a", description: "Left operand." },
      { name: "b", description: "Right operand." },
    ],
    minArgs: 2,
    maxArgs: 2,
    docUrl: `${BASE_DOC_URL}/dtl-functions-comparisons.html`,
  },
  {
    name: "gt",
    category: "Comparisons",
    kind: "expression",
    signature: "gt(a, b)",
    description: "Returns true if a is greater than b.",
    params: [
      { name: "a", description: "Left operand." },
      { name: "b", description: "Right operand." },
    ],
    minArgs: 2,
    maxArgs: 2,
    docUrl: `${BASE_DOC_URL}/dtl-functions-comparisons.html`,
  },
  {
    name: "gte",
    category: "Comparisons",
    kind: "expression",
    signature: "gte(a, b)",
    description: "Returns true if a is greater than or equal to b.",
    params: [
      { name: "a", description: "Left operand." },
      { name: "b", description: "Right operand." },
    ],
    minArgs: 2,
    maxArgs: 2,
    docUrl: `${BASE_DOC_URL}/dtl-functions-comparisons.html`,
  },
  {
    name: "lt",
    category: "Comparisons",
    kind: "expression",
    signature: "lt(a, b)",
    description: "Returns true if a is less than b.",
    params: [
      { name: "a", description: "Left operand." },
      { name: "b", description: "Right operand." },
    ],
    minArgs: 2,
    maxArgs: 2,
    docUrl: `${BASE_DOC_URL}/dtl-functions-comparisons.html`,
  },
  {
    name: "lte",
    category: "Comparisons",
    kind: "expression",
    signature: "lte(a, b)",
    description: "Returns true if a is less than or equal to b.",
    params: [
      { name: "a", description: "Left operand." },
      { name: "b", description: "Right operand." },
    ],
    minArgs: 2,
    maxArgs: 2,
    docUrl: `${BASE_DOC_URL}/dtl-functions-comparisons.html`,
  },

  // ─── CONDITIONALS ────────────────────────────────────────────────────────
  {
    name: "coalesce",
    category: "Conditionals",
    kind: "expression",
    signature: "coalesce(expr, ...)",
    description: "Returns the first non-null, non-empty value from the arguments.",
    params: [{ name: "expr", description: "One or more expressions to evaluate." }],
    minArgs: 1,
    maxArgs: null,
    docUrl: `${BASE_DOC_URL}/dtl-functions-conditionals.html`,
  },
  {
    name: "coalesce-args",
    category: "Conditionals",
    kind: "expression",
    signature: "coalesce-args(expr, ...)",
    description: "Returns the first non-null argument (does not flatten lists).",
    params: [{ name: "expr", description: "One or more expressions." }],
    minArgs: 1,
    maxArgs: null,
    docUrl: `${BASE_DOC_URL}/dtl-functions-conditionals.html`,
  },

  // ─── DATE AND TIME ───────────────────────────────────────────────────────
  {
    name: "now",
    category: "Date and time",
    kind: "expression",
    signature: "now()",
    description: "Returns the current UTC datetime.",
    params: [],
    minArgs: 0,
    maxArgs: 0,
    docUrl: `${BASE_DOC_URL}/dtl-functions-date-and-time.html`,
  },
  {
    name: "datetime",
    category: "Date and time",
    kind: "expression",
    signature: "datetime(value)",
    description: "Parses or converts value to a datetime object.",
    params: [{ name: "value", description: "ISO 8601 string or transit datetime." }],
    minArgs: 1,
    maxArgs: 1,
    docUrl: `${BASE_DOC_URL}/dtl-functions-date-and-time.html`,
  },
  {
    name: "datetime-parse",
    category: "Date and time",
    kind: "expression",
    signature: "datetime-parse(format, value)",
    description: "Parses value with the given format string to a datetime.",
    params: [
      { name: "format", description: "strptime-compatible format string." },
      { name: "value", description: "The string to parse." },
    ],
    minArgs: 2,
    maxArgs: 2,
    docUrl: `${BASE_DOC_URL}/dtl-functions-date-and-time.html`,
  },
  {
    name: "datetime-format",
    category: "Date and time",
    kind: "expression",
    signature: "datetime-format(format, datetime [, timezone])",
    description: "Formats a datetime value using the given format string.",
    params: [
      { name: "format", description: "strftime-compatible format string." },
      { name: "datetime", description: "A datetime value." },
      {
        name: "timezone",
        description: "Optional timezone identifier.",
        optional: true,
      },
    ],
    minArgs: 2,
    maxArgs: 3,
    docUrl: `${BASE_DOC_URL}/dtl-functions-date-and-time.html`,
  },
  {
    name: "datetime-diff",
    category: "Date and time",
    kind: "expression",
    signature: "datetime-diff(unit, datetime1, datetime2)",
    description: "Returns the difference between two datetimes in the given unit.",
    params: [
      {
        name: "unit",
        description: '"days", "hours", "minutes", "seconds", etc.',
      },
      { name: "datetime1", description: "First datetime." },
      { name: "datetime2", description: "Second datetime." },
    ],
    minArgs: 3,
    maxArgs: 3,
    docUrl: `${BASE_DOC_URL}/dtl-functions-date-and-time.html`,
  },
  {
    name: "datetime-plus",
    category: "Date and time",
    kind: "expression",
    signature: "datetime-plus(datetime, unit, amount)",
    description: "Adds amount of unit to the given datetime.",
    params: [
      { name: "datetime", description: "A datetime value." },
      {
        name: "unit",
        description: '"days", "hours", "minutes", "seconds", etc.',
      },
      { name: "amount", description: "Number to add (can be negative)." },
    ],
    minArgs: 3,
    maxArgs: 3,
    docUrl: `${BASE_DOC_URL}/dtl-functions-date-and-time.html`,
  },
  {
    name: "datetime-shift",
    category: "Date and time",
    kind: "expression",
    signature: "datetime-shift(datetime, from-timezone, to-timezone)",
    description: "Shifts a datetime between timezones.",
    params: [
      { name: "datetime", description: "A datetime value." },
      { name: "from-timezone", description: "Source timezone identifier." },
      { name: "to-timezone", description: "Target timezone identifier." },
    ],
    minArgs: 3,
    maxArgs: 3,
    docUrl: `${BASE_DOC_URL}/dtl-functions-date-and-time.html`,
  },
  {
    name: "is-datetime",
    category: "Date and time",
    kind: "expression",
    signature: "is-datetime(value)",
    description: "Returns true if value is a datetime object.",
    params: [{ name: "value", description: "The value to test." }],
    minArgs: 1,
    maxArgs: 1,
    docUrl: `${BASE_DOC_URL}/dtl-functions-date-and-time.html`,
  },

  // ─── DICTIONARIES ────────────────────────────────────────────────────────
  {
    name: "dict",
    category: "Dictionaries",
    kind: "expression",
    signature: "dict(key, value, ...)",
    description: "Creates a dictionary from alternating key-value arguments.",
    params: [{ name: "key-value-pairs", description: "Alternating keys and values." }],
    minArgs: 0,
    maxArgs: null,
    docUrl: `${BASE_DOC_URL}/dtl-functions-dictionaries.html`,
  },
  {
    name: "keys",
    category: "Dictionaries",
    kind: "expression",
    signature: "keys(dict)",
    description: "Returns the keys of a dictionary as a list.",
    params: [{ name: "dict", description: "A dictionary value." }],
    minArgs: 1,
    maxArgs: 1,
    docUrl: `${BASE_DOC_URL}/dtl-functions-dictionaries.html`,
  },
  {
    name: "values",
    category: "Dictionaries",
    kind: "expression",
    signature: "values(dict)",
    description: "Returns the values of a dictionary as a list.",
    params: [{ name: "dict", description: "A dictionary value." }],
    minArgs: 1,
    maxArgs: 1,
    docUrl: `${BASE_DOC_URL}/dtl-functions-dictionaries.html`,
  },
  {
    name: "items",
    category: "Dictionaries",
    kind: "expression",
    signature: "items(dict)",
    description: "Returns key-value pairs of a dictionary as a list of [key, value] lists.",
    params: [{ name: "dict", description: "A dictionary value." }],
    minArgs: 1,
    maxArgs: 1,
    docUrl: `${BASE_DOC_URL}/dtl-functions-dictionaries.html`,
  },
  {
    name: "key-values",
    category: "Dictionaries",
    kind: "expression",
    signature: "key-values(dict)",
    description: 'Returns key-value pairs as a list of {"key":k,"value":v} dicts.',
    params: [{ name: "dict", description: "A dictionary value." }],
    minArgs: 1,
    maxArgs: 1,
    docUrl: `${BASE_DOC_URL}/dtl-functions-dictionaries.html`,
  },
  {
    name: "has-key",
    category: "Dictionaries",
    kind: "expression",
    signature: "has-key(dict, key)",
    description: "Returns true if the dictionary contains the given key.",
    params: [
      { name: "dict", description: "A dictionary value." },
      { name: "key", description: "Key to check." },
    ],
    minArgs: 2,
    maxArgs: 2,
    docUrl: `${BASE_DOC_URL}/dtl-functions-dictionaries.html`,
  },
  {
    name: "is-dict",
    category: "Dictionaries",
    kind: "expression",
    signature: "is-dict(value)",
    description: "Returns true if value is a dictionary.",
    params: [{ name: "value", description: "The value to test." }],
    minArgs: 1,
    maxArgs: 1,
    docUrl: `${BASE_DOC_URL}/dtl-functions-dictionaries.html`,
  },
  {
    name: "path",
    category: "Dictionaries",
    kind: "expression",
    signature: "path(path, value)",
    description: "Follows a dot-separated path into a nested dict structure.",
    params: [
      { name: "path", description: "Dot-separated key path string." },
      { name: "value", description: "The dict or entity to traverse." },
    ],
    minArgs: 2,
    maxArgs: 2,
    docUrl: `${BASE_DOC_URL}/dtl-functions-dictionaries.html`,
  },
  {
    name: "apply",
    category: "Dictionaries",
    kind: "expression",
    signature: "apply(rule-id, entity)",
    description: "Applies a named DTL rule (defined in the same pipe) to an entity.",
    params: [
      { name: "rule-id", description: "The rule identifier string." },
      { name: "entity", description: "The entity to transform." },
    ],
    minArgs: 2,
    maxArgs: 2,
    docUrl: `${BASE_DOC_URL}/dtl-functions-dictionaries.html`,
  },
  {
    name: "apply-hops",
    category: "Dictionaries",
    kind: "expression",
    signature: "apply-hops(rule-id, hops-spec)",
    description: "Applies a named rule to entities fetched via hops.",
    params: [
      { name: "rule-id", description: "The rule identifier string." },
      { name: "hops-spec", description: "A hops specification object." },
    ],
    minArgs: 2,
    maxArgs: 2,
    docUrl: `${BASE_DOC_URL}/dtl-functions-dictionaries.html`,
  },
  {
    name: "apply-ns",
    category: "Dictionaries",
    kind: "expression",
    signature: "apply-ns(namespace, dict)",
    description: "Applies a namespace to all keys in a dictionary.",
    params: [
      {
        name: "namespace",
        description: "Namespace string to prefix keys with.",
      },
      { name: "dict", description: "A dictionary." },
    ],
    minArgs: 2,
    maxArgs: 2,
    docUrl: `${BASE_DOC_URL}/dtl-functions-dictionaries.html`,
  },
  {
    name: "strip-ns",
    category: "Dictionaries",
    kind: "expression",
    signature: "strip-ns(dict)",
    description: "Removes namespace prefixes from all keys in a dictionary.",
    params: [{ name: "dict", description: "A dictionary with namespaced keys." }],
    minArgs: 1,
    maxArgs: 1,
    docUrl: `${BASE_DOC_URL}/dtl-functions-dictionaries.html`,
  },

  // ─── ENCRYPTION ──────────────────────────────────────────────────────────
  {
    name: "encrypt",
    category: "Encryption",
    kind: "expression",
    signature: "encrypt(value)",
    description: "Encrypts a value using the datahub encryption key.",
    params: [{ name: "value", description: "The value to encrypt." }],
    minArgs: 1,
    maxArgs: 1,
    docUrl: `${BASE_DOC_URL}/dtl-functions-encryption.html`,
  },
  {
    name: "decrypt",
    category: "Encryption",
    kind: "expression",
    signature: "decrypt(value)",
    description: "Decrypts a value encrypted with the datahub encryption key.",
    params: [{ name: "value", description: "The encrypted value to decrypt." }],
    minArgs: 1,
    maxArgs: 1,
    docUrl: `${BASE_DOC_URL}/dtl-functions-encryption.html`,
  },
  {
    name: "encrypt-pgp",
    category: "Encryption",
    kind: "expression",
    signature: "encrypt-pgp(public-key, value)",
    description: "Encrypts value using PGP public key encryption.",
    params: [
      { name: "public-key", description: "PGP public key string." },
      { name: "value", description: "The value to encrypt." },
    ],
    minArgs: 2,
    maxArgs: 2,
    docUrl: `${BASE_DOC_URL}/dtl-functions-encryption.html`,
  },
  {
    name: "decrypt-pgp",
    category: "Encryption",
    kind: "expression",
    signature: "decrypt-pgp(private-key, value)",
    description: "Decrypts a PGP-encrypted value.",
    params: [
      { name: "private-key", description: "PGP private key string." },
      { name: "value", description: "The encrypted value." },
    ],
    minArgs: 2,
    maxArgs: 2,
    docUrl: `${BASE_DOC_URL}/dtl-functions-encryption.html`,
  },
  {
    name: "encrypt-pki",
    category: "Encryption",
    kind: "expression",
    signature: "encrypt-pki(public-key, value)",
    description: "Encrypts value using PKI public key encryption.",
    params: [
      { name: "public-key", description: "PKI public key string." },
      { name: "value", description: "The value to encrypt." },
    ],
    minArgs: 2,
    maxArgs: 2,
    docUrl: `${BASE_DOC_URL}/dtl-functions-encryption.html`,
  },
  {
    name: "decrypt-pki",
    category: "Encryption",
    kind: "expression",
    signature: "decrypt-pki(private-key, value)",
    description: "Decrypts a PKI-encrypted value.",
    params: [
      { name: "private-key", description: "PKI private key string." },
      { name: "value", description: "The encrypted value." },
    ],
    minArgs: 2,
    maxArgs: 2,
    docUrl: `${BASE_DOC_URL}/dtl-functions-encryption.html`,
  },

  // ─── HOPS ────────────────────────────────────────────────────────────────
  {
    name: "hops",
    category: "Hops",
    kind: "expression",
    signature: "hops(hops-spec)",
    description: "Performs a hop to retrieve related entities from another dataset.",
    params: [
      {
        name: "hops-spec",
        description: 'Object with "datasets", "where", and optionally "return" and "max-depth".',
      },
    ],
    minArgs: 1,
    maxArgs: 1,
    docUrl: `${BASE_DOC_URL}/dtl-functions-hops.html`,
  },
  {
    name: "lookup-entity",
    category: "Hops",
    kind: "expression",
    signature: "lookup-entity(dataset, id)",
    description: "Retrieves a single entity by _id from the given dataset.",
    params: [
      { name: "dataset", description: "Dataset name string." },
      { name: "id", description: "The _id value to look up." },
    ],
    minArgs: 2,
    maxArgs: 2,
    docUrl: `${BASE_DOC_URL}/dtl-functions-hops.html`,
  },

  // ─── JSON ────────────────────────────────────────────────────────────────
  {
    name: "json",
    category: "JSON",
    kind: "expression",
    signature: "json(value)",
    description: "Serializes value to a JSON string.",
    params: [{ name: "value", description: "The value to serialize." }],
    minArgs: 1,
    maxArgs: 1,
    docUrl: `${BASE_DOC_URL}/dtl-functions-json.html`,
  },
  {
    name: "json-parse",
    category: "JSON",
    kind: "expression",
    signature: "json-parse(string)",
    description: "Parses a JSON string into a value.",
    params: [{ name: "string", description: "A JSON-encoded string." }],
    minArgs: 1,
    maxArgs: 1,
    docUrl: `${BASE_DOC_URL}/dtl-functions-json.html`,
  },
  {
    name: "json-transit",
    category: "JSON",
    kind: "expression",
    signature: "json-transit(value)",
    description: "Serializes value using JSON Transit encoding.",
    params: [{ name: "value", description: "The value to encode." }],
    minArgs: 1,
    maxArgs: 1,
    docUrl: `${BASE_DOC_URL}/dtl-functions-json.html`,
  },
  {
    name: "json-transit-parse",
    category: "JSON",
    kind: "expression",
    signature: "json-transit-parse(string)",
    description: "Parses a JSON Transit-encoded string.",
    params: [{ name: "string", description: "A JSON Transit string." }],
    minArgs: 1,
    maxArgs: 1,
    docUrl: `${BASE_DOC_URL}/dtl-functions-json.html`,
  },

  // ─── LISTS ───────────────────────────────────────────────────────────────
  {
    name: "list",
    category: "Lists",
    kind: "expression",
    signature: "list(value, ...)",
    description: "Creates a list from the given values.",
    params: [{ name: "value", description: "One or more values." }],
    minArgs: 0,
    maxArgs: null,
    docUrl: `${BASE_DOC_URL}/dtl-functions-lists.html`,
  },
  {
    name: "map",
    category: "Lists",
    kind: "expression",
    signature: "map(list, expr)",
    description:
      "Transforms each element of the list using expr (which references _ for the current item).",
    params: [
      { name: "list", description: "A list to iterate over." },
      {
        name: "expr",
        description: "Expression evaluated for each element (use _ for current).",
      },
    ],
    minArgs: 2,
    maxArgs: 2,
    docUrl: `${BASE_DOC_URL}/dtl-functions-lists.html`,
  },
  {
    name: "map-dict",
    category: "Lists",
    kind: "expression",
    signature: "map-dict(key-fn, value-fn, list)",
    description: "Builds a dictionary by applying key-fn and value-fn to each list element.",
    params: [
      {
        name: "key-fn",
        description: "Expression producing the key (use _ for current item).",
      },
      { name: "value-fn", description: "Expression producing the value." },
      { name: "list", description: "A list to iterate over." },
    ],
    minArgs: 3,
    maxArgs: 3,
    docUrl: `${BASE_DOC_URL}/dtl-functions-lists.html`,
  },
  {
    name: "map-values",
    category: "Lists",
    kind: "expression",
    signature: "map-values(dict, expr)",
    description: "Transforms each value in the dictionary using expr.",
    params: [
      { name: "dict", description: "A dictionary." },
      {
        name: "expr",
        description: "Expression for each value (use _ for current value).",
      },
    ],
    minArgs: 2,
    maxArgs: 2,
    docUrl: `${BASE_DOC_URL}/dtl-functions-lists.html`,
  },
  {
    name: "first",
    category: "Lists",
    kind: "expression",
    signature: "first(list)",
    description: "Returns the first element of the list, or null if empty.",
    params: [{ name: "list", description: "A list value." }],
    minArgs: 1,
    maxArgs: 1,
    docUrl: `${BASE_DOC_URL}/dtl-functions-lists.html`,
  },
  {
    name: "last",
    category: "Lists",
    kind: "expression",
    signature: "last(list)",
    description: "Returns the last element of the list, or null if empty.",
    params: [{ name: "list", description: "A list value." }],
    minArgs: 1,
    maxArgs: 1,
    docUrl: `${BASE_DOC_URL}/dtl-functions-lists.html`,
  },
  {
    name: "nth",
    category: "Lists",
    kind: "expression",
    signature: "nth(list, n)",
    description: "Returns the element at zero-based index n.",
    params: [
      { name: "list", description: "A list value." },
      { name: "n", description: "Zero-based index." },
    ],
    minArgs: 2,
    maxArgs: 2,
    docUrl: `${BASE_DOC_URL}/dtl-functions-lists.html`,
  },
  {
    name: "count",
    category: "Lists",
    kind: "expression",
    signature: "count(list)",
    description: "Returns the number of elements in the list.",
    params: [{ name: "list", description: "A list value." }],
    minArgs: 1,
    maxArgs: 1,
    docUrl: `${BASE_DOC_URL}/dtl-functions-lists.html`,
  },
  {
    name: "distinct",
    category: "Lists",
    kind: "expression",
    signature: "distinct(list)",
    description: "Returns the list with duplicate values removed.",
    params: [{ name: "list", description: "A list value." }],
    minArgs: 1,
    maxArgs: 1,
    docUrl: `${BASE_DOC_URL}/dtl-functions-lists.html`,
  },
  {
    name: "flatten",
    category: "Lists",
    kind: "expression",
    signature: "flatten(list)",
    description: "Flattens one level of nested lists into a single list.",
    params: [{ name: "list", description: "A list that may contain nested lists." }],
    minArgs: 1,
    maxArgs: 1,
    docUrl: `${BASE_DOC_URL}/dtl-functions-lists.html`,
  },
  {
    name: "combine",
    category: "Lists",
    kind: "expression",
    signature: "combine(list, ...)",
    description: "Concatenates multiple lists into one.",
    params: [{ name: "list", description: "One or more lists to combine." }],
    minArgs: 1,
    maxArgs: null,
    docUrl: `${BASE_DOC_URL}/dtl-functions-lists.html`,
  },
  {
    name: "group",
    category: "Lists",
    kind: "expression",
    signature: "group(list)",
    description: "Groups a list of [key, value] pairs into a dict of key → [values].",
    params: [{ name: "list", description: "A list of [key, value] pairs." }],
    minArgs: 1,
    maxArgs: 1,
    docUrl: `${BASE_DOC_URL}/dtl-functions-lists.html`,
  },
  {
    name: "group-by",
    category: "Lists",
    kind: "expression",
    signature: "group-by(key-fn, list)",
    description: "Groups list elements by the key produced by key-fn.",
    params: [
      { name: "key-fn", description: "Expression producing the group key." },
      { name: "list", description: "A list to group." },
    ],
    minArgs: 2,
    maxArgs: 2,
    docUrl: `${BASE_DOC_URL}/dtl-functions-lists.html`,
  },
  {
    name: "sorted",
    category: "Lists",
    kind: "expression",
    signature: "sorted(list)",
    description: "Returns the list sorted in ascending order.",
    params: [{ name: "list", description: "A list to sort." }],
    minArgs: 1,
    maxArgs: 1,
    docUrl: `${BASE_DOC_URL}/dtl-functions-lists.html`,
  },
  {
    name: "sorted-descending",
    category: "Lists",
    kind: "expression",
    signature: "sorted-descending(list)",
    description: "Returns the list sorted in descending order.",
    params: [{ name: "list", description: "A list to sort." }],
    minArgs: 1,
    maxArgs: 1,
    docUrl: `${BASE_DOC_URL}/dtl-functions-lists.html`,
  },
  {
    name: "reversed",
    category: "Lists",
    kind: "expression",
    signature: "reversed(list)",
    description: "Returns the list in reversed order.",
    params: [{ name: "list", description: "A list to reverse." }],
    minArgs: 1,
    maxArgs: 1,
    docUrl: `${BASE_DOC_URL}/dtl-functions-lists.html`,
  },
  {
    name: "slice",
    category: "Lists",
    kind: "expression",
    signature: "slice(list, start [, end])",
    description: "Returns a slice of the list from start to end (exclusive).",
    params: [
      { name: "list", description: "A list." },
      { name: "start", description: "Start index (zero-based)." },
      { name: "end", description: "End index (exclusive).", optional: true },
    ],
    minArgs: 2,
    maxArgs: 3,
    docUrl: `${BASE_DOC_URL}/dtl-functions-lists.html`,
  },
  {
    name: "range",
    category: "Lists",
    kind: "expression",
    signature: "range(end) | range(start, end [, step])",
    description: "Returns a list of integers from start to end.",
    params: [
      { name: "start", description: "Start value (default 0)." },
      { name: "end", description: "End value (exclusive)." },
      { name: "step", description: "Step size (default 1).", optional: true },
    ],
    minArgs: 1,
    maxArgs: 3,
    docUrl: `${BASE_DOC_URL}/dtl-functions-lists.html`,
  },
  {
    name: "in",
    category: "Lists",
    kind: "expression",
    signature: "in(value, list)",
    description: "Returns true if value is found in the list.",
    params: [
      { name: "value", description: "Value to search for." },
      { name: "list", description: "List to search." },
    ],
    minArgs: 2,
    maxArgs: 2,
    docUrl: `${BASE_DOC_URL}/dtl-functions-lists.html`,
  },
  {
    name: "insert",
    category: "Lists",
    kind: "expression",
    signature: "insert(list, index, value)",
    description: "Inserts value at the given index in the list.",
    params: [
      { name: "list", description: "A list." },
      { name: "index", description: "Insertion position." },
      { name: "value", description: "The value to insert." },
    ],
    minArgs: 3,
    maxArgs: 3,
    docUrl: `${BASE_DOC_URL}/dtl-functions-lists.html`,
  },
  {
    name: "enumerate",
    category: "Lists",
    kind: "expression",
    signature: "enumerate(list)",
    description: "Returns a list of [index, element] pairs.",
    params: [{ name: "list", description: "A list to enumerate." }],
    minArgs: 1,
    maxArgs: 1,
    docUrl: `${BASE_DOC_URL}/dtl-functions-lists.html`,
  },
  {
    name: "is-list",
    category: "Lists",
    kind: "expression",
    signature: "is-list(value)",
    description: "Returns true if value is a list.",
    params: [{ name: "value", description: "The value to test." }],
    minArgs: 1,
    maxArgs: 1,
    docUrl: `${BASE_DOC_URL}/dtl-functions-lists.html`,
  },
  {
    name: "is-empty",
    category: "Lists",
    kind: "expression",
    signature: "is-empty(list)",
    description: "Returns true if the list is null or empty.",
    params: [{ name: "list", description: "The list to test." }],
    minArgs: 1,
    maxArgs: 1,
    docUrl: `${BASE_DOC_URL}/dtl-functions-lists.html`,
  },
  {
    name: "is-not-empty",
    category: "Lists",
    kind: "expression",
    signature: "is-not-empty(list)",
    description: "Returns true if the list is non-null and non-empty.",
    params: [{ name: "list", description: "The list to test." }],
    minArgs: 1,
    maxArgs: 1,
    docUrl: `${BASE_DOC_URL}/dtl-functions-lists.html`,
  },
  {
    name: "sum",
    category: "Lists",
    kind: "expression",
    signature: "sum(list)",
    description: "Returns the sum of all numeric elements in the list.",
    params: [{ name: "list", description: "A list of numbers." }],
    minArgs: 1,
    maxArgs: 1,
    docUrl: `${BASE_DOC_URL}/dtl-functions-lists.html`,
  },
  {
    name: "min",
    category: "Lists",
    kind: "expression",
    signature: "min(list)",
    description: "Returns the minimum value in the list.",
    params: [{ name: "list", description: "A list of comparable values." }],
    minArgs: 1,
    maxArgs: 1,
    docUrl: `${BASE_DOC_URL}/dtl-functions-lists.html`,
  },
  {
    name: "max",
    category: "Lists",
    kind: "expression",
    signature: "max(list)",
    description: "Returns the maximum value in the list.",
    params: [{ name: "list", description: "A list of comparable values." }],
    minArgs: 1,
    maxArgs: 1,
    docUrl: `${BASE_DOC_URL}/dtl-functions-lists.html`,
  },

  // ─── MATH ────────────────────────────────────────────────────────────────
  {
    name: "+",
    category: "Math",
    kind: "expression",
    signature: "+(a, b, ...)",
    description: "Adds numbers together.",
    params: [{ name: "values", description: "Numeric values to add." }],
    minArgs: 2,
    maxArgs: null,
    docUrl: `${BASE_DOC_URL}/dtl-functions-math.html`,
  },
  {
    name: "-",
    category: "Math",
    kind: "expression",
    signature: "-(a, b)",
    description: "Subtracts b from a.",
    params: [
      { name: "a", description: "Minuend." },
      { name: "b", description: "Subtrahend." },
    ],
    minArgs: 1,
    maxArgs: 2,
    docUrl: `${BASE_DOC_URL}/dtl-functions-math.html`,
  },
  {
    name: "*",
    category: "Math",
    kind: "expression",
    signature: "*(a, b, ...)",
    description: "Multiplies numbers.",
    params: [{ name: "values", description: "Numeric values to multiply." }],
    minArgs: 2,
    maxArgs: null,
    docUrl: `${BASE_DOC_URL}/dtl-functions-math.html`,
  },
  {
    name: "/",
    category: "Math",
    kind: "expression",
    signature: "/(a, b)",
    description: "Divides a by b.",
    params: [
      { name: "a", description: "Numerator." },
      { name: "b", description: "Denominator." },
    ],
    minArgs: 2,
    maxArgs: 2,
    docUrl: `${BASE_DOC_URL}/dtl-functions-math.html`,
  },
  {
    name: "%",
    category: "Math",
    kind: "expression",
    signature: "%(a, b)",
    description: "Returns a modulo b.",
    params: [
      { name: "a", description: "Dividend." },
      { name: "b", description: "Divisor." },
    ],
    minArgs: 2,
    maxArgs: 2,
    docUrl: `${BASE_DOC_URL}/dtl-functions-math.html`,
  },
  {
    name: "^",
    category: "Math",
    kind: "expression",
    signature: "^(base, exponent)",
    description: "Returns base raised to the power of exponent.",
    params: [
      { name: "base", description: "Base number." },
      { name: "exponent", description: "Exponent." },
    ],
    minArgs: 2,
    maxArgs: 2,
    docUrl: `${BASE_DOC_URL}/dtl-functions-math.html`,
  },
  {
    name: "abs",
    category: "Math",
    kind: "expression",
    signature: "abs(value)",
    description: "Returns the absolute value.",
    params: [{ name: "value", description: "A number." }],
    minArgs: 1,
    maxArgs: 1,
    docUrl: `${BASE_DOC_URL}/dtl-functions-math.html`,
  },
  {
    name: "ceil",
    category: "Math",
    kind: "expression",
    signature: "ceil(value)",
    description: "Returns the ceiling (round up) of the value.",
    params: [{ name: "value", description: "A number." }],
    minArgs: 1,
    maxArgs: 1,
    docUrl: `${BASE_DOC_URL}/dtl-functions-math.html`,
  },
  {
    name: "floor",
    category: "Math",
    kind: "expression",
    signature: "floor(value)",
    description: "Returns the floor (round down) of the value.",
    params: [{ name: "value", description: "A number." }],
    minArgs: 1,
    maxArgs: 1,
    docUrl: `${BASE_DOC_URL}/dtl-functions-math.html`,
  },
  {
    name: "round",
    category: "Math",
    kind: "expression",
    signature: "round(value [, ndigits])",
    description: "Rounds value to the given number of decimal digits.",
    params: [
      { name: "value", description: "A number." },
      {
        name: "ndigits",
        description: "Number of decimal places (default 0).",
        optional: true,
      },
    ],
    minArgs: 1,
    maxArgs: 2,
    docUrl: `${BASE_DOC_URL}/dtl-functions-math.html`,
  },
  {
    name: "sqrt",
    category: "Math",
    kind: "expression",
    signature: "sqrt(value)",
    description: "Returns the square root of value.",
    params: [{ name: "value", description: "A non-negative number." }],
    minArgs: 1,
    maxArgs: 1,
    docUrl: `${BASE_DOC_URL}/dtl-functions-math.html`,
  },
  {
    name: "pow",
    category: "Math",
    kind: "expression",
    signature: "pow(base, exponent)",
    description: "Returns base raised to exponent (alias of ^).",
    params: [
      { name: "base", description: "Base number." },
      { name: "exponent", description: "Exponent." },
    ],
    minArgs: 2,
    maxArgs: 2,
    docUrl: `${BASE_DOC_URL}/dtl-functions-math.html`,
  },
  {
    name: "cos",
    category: "Math",
    kind: "expression",
    signature: "cos(radians)",
    description: "Cosine.",
    params: [{ name: "radians", description: "Angle in radians." }],
    minArgs: 1,
    maxArgs: 1,
    docUrl: `${BASE_DOC_URL}/dtl-functions-math.html`,
  },
  {
    name: "sin",
    category: "Math",
    kind: "expression",
    signature: "sin(radians)",
    description: "Sine.",
    params: [{ name: "radians", description: "Angle in radians." }],
    minArgs: 1,
    maxArgs: 1,
    docUrl: `${BASE_DOC_URL}/dtl-functions-math.html`,
  },
  {
    name: "tan",
    category: "Math",
    kind: "expression",
    signature: "tan(radians)",
    description: "Tangent.",
    params: [{ name: "radians", description: "Angle in radians." }],
    minArgs: 1,
    maxArgs: 1,
    docUrl: `${BASE_DOC_URL}/dtl-functions-math.html`,
  },

  // ─── MISC ────────────────────────────────────────────────────────────────
  {
    name: "hash128",
    category: "Misc",
    kind: "expression",
    signature: "hash128(value)",
    description: "Returns a 128-bit hash of the value as a hex string.",
    params: [{ name: "value", description: "The value to hash." }],
    minArgs: 1,
    maxArgs: 1,
    docUrl: `${BASE_DOC_URL}/dtl-functions-misc.html`,
  },
  {
    name: "literal",
    category: "Misc",
    kind: "expression",
    signature: "literal(value)",
    description: "Returns value as a literal (prevents further evaluation).",
    params: [{ name: "value", description: "A literal value." }],
    minArgs: 1,
    maxArgs: 1,
    docUrl: `${BASE_DOC_URL}/dtl-functions-misc.html`,
  },
  {
    name: "tuples",
    category: "Misc",
    kind: "expression",
    signature: "tuples(list1, list2)",
    description: "Zips two lists into a list of [a, b] pairs.",
    params: [
      { name: "list1", description: "First list." },
      { name: "list2", description: "Second list." },
    ],
    minArgs: 2,
    maxArgs: 2,
    docUrl: `${BASE_DOC_URL}/dtl-functions-misc.html`,
  },
  {
    name: "completeness",
    category: "Misc",
    kind: "expression",
    signature: "completeness(value)",
    description: "Returns a completeness score for value (fraction of non-null leaf values).",
    params: [{ name: "value", description: "A dict or entity." }],
    minArgs: 1,
    maxArgs: 1,
    docUrl: `${BASE_DOC_URL}/dtl-functions-misc.html`,
  },
  {
    name: "is-changed",
    category: "Misc",
    kind: "expression",
    signature: "is-changed(property)",
    description: "Returns true if the source property value differs from the previous version.",
    params: [{ name: "property", description: "A property path expression." }],
    minArgs: 1,
    maxArgs: 1,
    docUrl: `${BASE_DOC_URL}/dtl-functions-misc.html`,
  },

  // ─── NAMESPACED IDENTIFIERS ──────────────────────────────────────────────
  {
    name: "ni",
    category: "Namespaced identifiers",
    kind: "expression",
    signature: "ni(namespace, id)",
    description: "Creates a namespaced identifier.",
    params: [
      { name: "namespace", description: "Namespace string." },
      { name: "id", description: "Identifier string." },
    ],
    minArgs: 2,
    maxArgs: 2,
    docUrl: `${BASE_DOC_URL}/dtl-functions-namespaced-identifiers.html`,
  },
  {
    name: "ni-id",
    category: "Namespaced identifiers",
    kind: "expression",
    signature: "ni-id(ni)",
    description: "Extracts the local identifier part from a namespaced identifier.",
    params: [{ name: "ni", description: "A namespaced identifier." }],
    minArgs: 1,
    maxArgs: 1,
    docUrl: `${BASE_DOC_URL}/dtl-functions-namespaced-identifiers.html`,
  },
  {
    name: "ni-ns",
    category: "Namespaced identifiers",
    kind: "expression",
    signature: "ni-ns(ni)",
    description: "Extracts the namespace part from a namespaced identifier.",
    params: [{ name: "ni", description: "A namespaced identifier." }],
    minArgs: 1,
    maxArgs: 1,
    docUrl: `${BASE_DOC_URL}/dtl-functions-namespaced-identifiers.html`,
  },
  {
    name: "is-ni",
    category: "Namespaced identifiers",
    kind: "expression",
    signature: "is-ni(value)",
    description: "Returns true if value is a namespaced identifier.",
    params: [{ name: "value", description: "The value to test." }],
    minArgs: 1,
    maxArgs: 1,
    docUrl: `${BASE_DOC_URL}/dtl-functions-namespaced-identifiers.html`,
  },

  // ─── NULLS ───────────────────────────────────────────────────────────────
  {
    name: "is-null",
    category: "Nulls",
    kind: "expression",
    signature: "is-null(value)",
    description: "Returns true if value is null.",
    params: [{ name: "value", description: "The value to test." }],
    minArgs: 1,
    maxArgs: 1,
    docUrl: `${BASE_DOC_URL}/dtl-functions-nulls.html`,
  },
  {
    name: "is-not-null",
    category: "Nulls",
    kind: "expression",
    signature: "is-not-null(value)",
    description: "Returns true if value is not null.",
    params: [{ name: "value", description: "The value to test." }],
    minArgs: 1,
    maxArgs: 1,
    docUrl: `${BASE_DOC_URL}/dtl-functions-nulls.html`,
  },
  {
    name: "if-null",
    category: "Nulls",
    kind: "expression",
    signature: "if-null(value, default)",
    description: "Returns value if non-null, otherwise returns default.",
    params: [
      { name: "value", description: "The value to check." },
      { name: "default", description: "Fallback value when null." },
    ],
    minArgs: 2,
    maxArgs: 2,
    docUrl: `${BASE_DOC_URL}/dtl-functions-nulls.html`,
  },

  // ─── NUMBERS ─────────────────────────────────────────────────────────────
  {
    name: "integer",
    category: "Numbers",
    kind: "expression",
    signature: "integer(value)",
    description: "Converts value to an integer.",
    params: [{ name: "value", description: "The value to convert." }],
    minArgs: 1,
    maxArgs: 1,
    docUrl: `${BASE_DOC_URL}/dtl-functions-numbers.html`,
  },
  {
    name: "float",
    category: "Numbers",
    kind: "expression",
    signature: "float(value)",
    description: "Converts value to a float.",
    params: [{ name: "value", description: "The value to convert." }],
    minArgs: 1,
    maxArgs: 1,
    docUrl: `${BASE_DOC_URL}/dtl-functions-numbers.html`,
  },
  {
    name: "decimal",
    category: "Numbers",
    kind: "expression",
    signature: "decimal(value)",
    description: "Converts value to a decimal.",
    params: [{ name: "value", description: "The value to convert." }],
    minArgs: 1,
    maxArgs: 1,
    docUrl: `${BASE_DOC_URL}/dtl-functions-numbers.html`,
  },
  {
    name: "hex",
    category: "Numbers",
    kind: "expression",
    signature: "hex(value)",
    description: "Returns a hexadecimal string representation of an integer.",
    params: [{ name: "value", description: "An integer." }],
    minArgs: 1,
    maxArgs: 1,
    docUrl: `${BASE_DOC_URL}/dtl-functions-numbers.html`,
  },
  {
    name: "is-integer",
    category: "Numbers",
    kind: "expression",
    signature: "is-integer(value)",
    description: "Returns true if value is an integer.",
    params: [{ name: "value", description: "The value to test." }],
    minArgs: 1,
    maxArgs: 1,
    docUrl: `${BASE_DOC_URL}/dtl-functions-numbers.html`,
  },
  {
    name: "is-float",
    category: "Numbers",
    kind: "expression",
    signature: "is-float(value)",
    description: "Returns true if value is a float.",
    params: [{ name: "value", description: "The value to test." }],
    minArgs: 1,
    maxArgs: 1,
    docUrl: `${BASE_DOC_URL}/dtl-functions-numbers.html`,
  },
  {
    name: "is-decimal",
    category: "Numbers",
    kind: "expression",
    signature: "is-decimal(value)",
    description: "Returns true if value is a decimal.",
    params: [{ name: "value", description: "The value to test." }],
    minArgs: 1,
    maxArgs: 1,
    docUrl: `${BASE_DOC_URL}/dtl-functions-numbers.html`,
  },

  // ─── PHONENUMBERS ────────────────────────────────────────────────────────
  {
    name: "phonenumber-parse",
    category: "Phonenumbers",
    kind: "expression",
    signature: "phonenumber-parse(number [, region])",
    description: "Parses a phone number string into a structured dict.",
    params: [
      { name: "number", description: "Phone number string." },
      { name: "region", description: "ISO country code hint.", optional: true },
    ],
    minArgs: 1,
    maxArgs: 2,
    docUrl: `${BASE_DOC_URL}/dtl-functions-phonenumbers.html`,
  },
  {
    name: "phonenumber-format",
    category: "Phonenumbers",
    kind: "expression",
    signature: "phonenumber-format(format, phonenumber)",
    description: "Formats a parsed phone number into a string.",
    params: [
      {
        name: "format",
        description: '"E164", "INTERNATIONAL", "NATIONAL", "RFC3966".',
      },
      { name: "phonenumber", description: "Parsed phone number dict." },
    ],
    minArgs: 2,
    maxArgs: 2,
    docUrl: `${BASE_DOC_URL}/dtl-functions-phonenumbers.html`,
  },

  // ─── SETS ────────────────────────────────────────────────────────────────
  {
    name: "union",
    category: "Sets",
    kind: "expression",
    signature: "union(set1, set2)",
    description: "Returns the union of two sets (lists).",
    params: [
      { name: "set1", description: "First set." },
      { name: "set2", description: "Second set." },
    ],
    minArgs: 2,
    maxArgs: 2,
    docUrl: `${BASE_DOC_URL}/dtl-functions-sets.html`,
  },
  {
    name: "intersection",
    category: "Sets",
    kind: "expression",
    signature: "intersection(set1, set2)",
    description: "Returns the intersection of two sets.",
    params: [
      { name: "set1", description: "First set." },
      { name: "set2", description: "Second set." },
    ],
    minArgs: 2,
    maxArgs: 2,
    docUrl: `${BASE_DOC_URL}/dtl-functions-sets.html`,
  },
  {
    name: "difference",
    category: "Sets",
    kind: "expression",
    signature: "difference(set1, set2)",
    description: "Returns elements in set1 not present in set2.",
    params: [
      { name: "set1", description: "First set." },
      { name: "set2", description: "Second set." },
    ],
    minArgs: 2,
    maxArgs: 2,
    docUrl: `${BASE_DOC_URL}/dtl-functions-sets.html`,
  },
  {
    name: "intersects",
    category: "Sets",
    kind: "expression",
    signature: "intersects(set1, set2)",
    description: "Returns true if the two sets share at least one element.",
    params: [
      { name: "set1", description: "First set." },
      { name: "set2", description: "Second set." },
    ],
    minArgs: 2,
    maxArgs: 2,
    docUrl: `${BASE_DOC_URL}/dtl-functions-sets.html`,
  },

  // ─── STRINGS ─────────────────────────────────────────────────────────────
  {
    name: "concat",
    category: "Strings",
    kind: "expression",
    signature: "concat(value, ...)",
    description: "Concatenates values into a single string.",
    params: [{ name: "value", description: "One or more values to concatenate." }],
    minArgs: 1,
    maxArgs: null,
    docUrl: `${BASE_DOC_URL}/dtl-functions-strings.html`,
  },
  {
    name: "join",
    category: "Strings",
    kind: "expression",
    signature: "join(separator, list)",
    description: "Joins list elements into a string with separator.",
    params: [
      { name: "separator", description: "String separator." },
      { name: "list", description: "A list of values to join." },
    ],
    minArgs: 2,
    maxArgs: 2,
    docUrl: `${BASE_DOC_URL}/dtl-functions-strings.html`,
  },
  {
    name: "split",
    category: "Strings",
    kind: "expression",
    signature: "split(separator, string)",
    description: "Splits string by separator into a list.",
    params: [
      { name: "separator", description: "Delimiter string." },
      { name: "string", description: "The string to split." },
    ],
    minArgs: 2,
    maxArgs: 2,
    docUrl: `${BASE_DOC_URL}/dtl-functions-strings.html`,
  },
  {
    name: "upper",
    category: "Strings",
    kind: "expression",
    signature: "upper(string)",
    description: "Converts string to upper case.",
    params: [{ name: "string", description: "A string." }],
    minArgs: 1,
    maxArgs: 1,
    docUrl: `${BASE_DOC_URL}/dtl-functions-strings.html`,
  },
  {
    name: "lower",
    category: "Strings",
    kind: "expression",
    signature: "lower(string)",
    description: "Converts string to lower case.",
    params: [{ name: "string", description: "A string." }],
    minArgs: 1,
    maxArgs: 1,
    docUrl: `${BASE_DOC_URL}/dtl-functions-strings.html`,
  },
  {
    name: "strip",
    category: "Strings",
    kind: "expression",
    signature: "strip(string)",
    description: "Removes leading and trailing whitespace.",
    params: [{ name: "string", description: "A string." }],
    minArgs: 1,
    maxArgs: 1,
    docUrl: `${BASE_DOC_URL}/dtl-functions-strings.html`,
  },
  {
    name: "lstrip",
    category: "Strings",
    kind: "expression",
    signature: "lstrip(string)",
    description: "Removes leading whitespace.",
    params: [{ name: "string", description: "A string." }],
    minArgs: 1,
    maxArgs: 1,
    docUrl: `${BASE_DOC_URL}/dtl-functions-strings.html`,
  },
  {
    name: "rstrip",
    category: "Strings",
    kind: "expression",
    signature: "rstrip(string)",
    description: "Removes trailing whitespace.",
    params: [{ name: "string", description: "A string." }],
    minArgs: 1,
    maxArgs: 1,
    docUrl: `${BASE_DOC_URL}/dtl-functions-strings.html`,
  },
  {
    name: "replace",
    category: "Strings",
    kind: "expression",
    signature: "replace(search, replacement, string)",
    description: "Replaces all occurrences of search with replacement in string.",
    params: [
      { name: "search", description: "String to find." },
      { name: "replacement", description: "Replacement string." },
      { name: "string", description: "The string to process." },
    ],
    minArgs: 3,
    maxArgs: 3,
    docUrl: `${BASE_DOC_URL}/dtl-functions-strings.html`,
  },
  {
    name: "substring",
    category: "Strings",
    kind: "expression",
    signature: "substring(string, start [, end])",
    description: "Returns a substring from start to end.",
    params: [
      { name: "string", description: "A string." },
      { name: "start", description: "Start index." },
      { name: "end", description: "End index (exclusive).", optional: true },
    ],
    minArgs: 2,
    maxArgs: 3,
    docUrl: `${BASE_DOC_URL}/dtl-functions-strings.html`,
  },
  {
    name: "length",
    category: "Strings",
    kind: "expression",
    signature: "length(string)",
    description: "Returns the character length of the string.",
    params: [{ name: "string", description: "A string." }],
    minArgs: 1,
    maxArgs: 1,
    docUrl: `${BASE_DOC_URL}/dtl-functions-strings.html`,
  },
  {
    name: "matches",
    category: "Strings",
    kind: "expression",
    signature: "matches(pattern, string)",
    description: "Returns true if string matches the regex pattern.",
    params: [
      { name: "pattern", description: "A regex pattern string." },
      { name: "string", description: "The string to test." },
    ],
    minArgs: 2,
    maxArgs: 2,
    docUrl: `${BASE_DOC_URL}/dtl-functions-strings.html`,
  },
  {
    name: "string",
    category: "Strings",
    kind: "expression",
    signature: "string(value)",
    description: "Converts value to a string.",
    params: [{ name: "value", description: "The value to convert." }],
    minArgs: 1,
    maxArgs: 1,
    docUrl: `${BASE_DOC_URL}/dtl-functions-strings.html`,
  },
  {
    name: "is-string",
    category: "Strings",
    kind: "expression",
    signature: "is-string(value)",
    description: "Returns true if value is a string.",
    params: [{ name: "value", description: "The value to test." }],
    minArgs: 1,
    maxArgs: 1,
    docUrl: `${BASE_DOC_URL}/dtl-functions-strings.html`,
  },
  {
    name: "ljust",
    category: "Strings",
    kind: "expression",
    signature: "ljust(string, width [, fill])",
    description: "Left-justifies string within a field of given width.",
    params: [
      { name: "string", description: "String to pad." },
      { name: "width", description: "Total width." },
      {
        name: "fill",
        description: "Fill character (default space).",
        optional: true,
      },
    ],
    minArgs: 2,
    maxArgs: 3,
    docUrl: `${BASE_DOC_URL}/dtl-functions-strings.html`,
  },
  {
    name: "rjust",
    category: "Strings",
    kind: "expression",
    signature: "rjust(string, width [, fill])",
    description: "Right-justifies string within a field of given width.",
    params: [
      { name: "string", description: "String to pad." },
      { name: "width", description: "Total width." },
      {
        name: "fill",
        description: "Fill character (default space).",
        optional: true,
      },
    ],
    minArgs: 2,
    maxArgs: 3,
    docUrl: `${BASE_DOC_URL}/dtl-functions-strings.html`,
  },

  // ─── URIs ────────────────────────────────────────────────────────────────
  {
    name: "uri",
    category: "URIs",
    kind: "expression",
    signature: "uri(value)",
    description: "Creates a URI from value.",
    params: [{ name: "value", description: "A URI string." }],
    minArgs: 1,
    maxArgs: 1,
    docUrl: `${BASE_DOC_URL}/dtl-functions-uris.html`,
  },
  {
    name: "is-uri",
    category: "URIs",
    kind: "expression",
    signature: "is-uri(value)",
    description: "Returns true if value is a URI.",
    params: [{ name: "value", description: "The value to test." }],
    minArgs: 1,
    maxArgs: 1,
    docUrl: `${BASE_DOC_URL}/dtl-functions-uris.html`,
  },
  {
    name: "url-quote",
    category: "URIs",
    kind: "expression",
    signature: "url-quote(string)",
    description: "URL-encodes the string.",
    params: [{ name: "string", description: "String to encode." }],
    minArgs: 1,
    maxArgs: 1,
    docUrl: `${BASE_DOC_URL}/dtl-functions-uris.html`,
  },
  {
    name: "url-unquote",
    category: "URIs",
    kind: "expression",
    signature: "url-unquote(string)",
    description: "URL-decodes the string.",
    params: [{ name: "string", description: "String to decode." }],
    minArgs: 1,
    maxArgs: 1,
    docUrl: `${BASE_DOC_URL}/dtl-functions-uris.html`,
  },

  // ─── UUIDs ───────────────────────────────────────────────────────────────
  {
    name: "uuid",
    category: "UUIDs",
    kind: "expression",
    signature: "uuid()",
    description: "Generates a new random UUID string.",
    params: [],
    minArgs: 0,
    maxArgs: 0,
    docUrl: `${BASE_DOC_URL}/dtl-functions-uuids.html`,
  },
  {
    name: "is-uuid",
    category: "UUIDs",
    kind: "expression",
    signature: "is-uuid(value)",
    description: "Returns true if value is a UUID string.",
    params: [{ name: "value", description: "The value to test." }],
    minArgs: 1,
    maxArgs: 1,
    docUrl: `${BASE_DOC_URL}/dtl-functions-uuids.html`,
  },
];

// ---------------------------------------------------------------------------
// Index for O(1) lookups
// ---------------------------------------------------------------------------
const INDEX = new Map<string, DtlFunction>(FUNCTIONS.map((f) => [f.name, f]));

// ---------------------------------------------------------------------------
// Public API
// ---------------------------------------------------------------------------

/** Returns the definition for the given function name, or undefined if unknown. */
export const getDtlFunction = (name: string): DtlFunction | undefined => INDEX.get(name);

/** Returns all registered DTL functions. */
export const getAllFunctions = (): DtlFunction[] => FUNCTIONS;

/** Returns all transform functions (those with side-effects). */
export const getTransformFunctions = (): DtlFunction[] =>
  FUNCTIONS.filter((f) => f.kind === "transform");

/** Returns all expression functions (no side-effects, return values). */
export const getExpressionFunctions = (): DtlFunction[] =>
  FUNCTIONS.filter((f) => f.kind === "expression");

/** Returns all functions in a given category. */
export const getFunctionsByCategory = (category: DtlCategory): DtlFunction[] =>
  FUNCTIONS.filter((f) => f.category === category);

/** Returns all known function names. */
export const getAllFunctionNames = (): string[] => FUNCTIONS.map((f) => f.name);

/** Returns true if the given name is a known DTL function. */
export const isKnownFunction = (name: string): boolean => INDEX.has(name);

/** Built-in DTL variable descriptions. */
export const DTL_VARIABLES: Record<string, string> = {
  _S: "Source entity — the input entity being processed by the transform.",
  _T: "Target entity — the entity being constructed by the transform.",
  _P: "Parent context — available inside `apply` functions, refers to the parent entity.",
  _R: "Root context — contains both `_S` and `_T`, accessible at any nesting depth.",
  _B: "Request context — holds variables defined by URL parameters in HTTP endpoint sinks.",
  _: "Current value — refers to the current element in functional expressions like `map` and `filter`.",
};

/** Sesam entity reserved fields. */
export const ENTITY_RESERVED_FIELDS = [
  "_id",
  "_deleted",
  "_filtered",
  "_hash",
  "_previous",
  "_tracked",
  "_ts",
  "_updated",
  "$children",
  "$ids",
  "$replaced",
];
